module.exports = [
  ["BE001","Production de pétrole brut","Pétrole","Mtep","Métropole","Réelles","Production primaire"],
  ["BE002","Importations de pétrole brut","Pétrole","Mtep","Métropole","Réelles","Importations"],
  ["BE003","Exportations de pétrole brut","Pétrole","Mtep","Métropole","Réelles","Exportations"],
  ["BE004","Variations de stocks de pétrole brut (stocks au 1er janvier N - stocks au 31 décembre N)","Pétrole","Mtep","Métropole","Réelles","Stocks"],
  ["BE005","Disponibilités (Consommation primaire) en pétrole brut","Pétrole","Mtep","Métropole","Réelles","Consommation primaire"],
  ["BE006","Importations de produits raffinés","Pétrole","Mtep","Métropole","Réelles","Importations"],
  ["BE007","Exportations de produits raffinés","Pétrole","Mtep","Métropole","Réelles","Exportations"],
  ["BE008","Variations de stocks de produits raffinés (stocks au 1er janvier N - stocks au 31 décembre N)","Pétrole","Mtep","Métropole","Réelles","Stocks"],
  ["BE009","Soutes maritimes internationales (produits raffinés)","Pétrole","Mtep","Métropole","Réelles","Soutes"],
  ["BE010","Soutes aériennes internationales (produits raffinés)","Pétrole","Mtep","Métropole","Réelles","Soutes"],
  ["BE011","Consommation primaire de pétrole (Total brut et raffinés)","Pétrole","Mtep","Métropole","Réelles","Consommation primaire"],
  ["BE012","Consommation de pétrole brut des raffineries","Pétrole","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE013","Consommation de produits raffinés pour la production d'électricité seule","Pétrole","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE014","Consommation de produits raffinés pour la cogénération","Pétrole","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE015","Consommation de produits raffinés pour la production de chaleur seule","Pétrole","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE016","Production brute des raffineries en produits raffinés","Pétrole","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE017","Autoconsommation des raffineries en produits raffinés (hors production d'électricité et chaleur)","Pétrole","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE018","Consommation finale à usage énergétique de produits raffinés","Pétrole","Mtep","Métropole","Réelles","Consommation finale énergétique"],
  ["BE019","Consommation finale de produits raffinés dans l'industrie","Pétrole","Mtep","Métropole","Réelles","Industrie"],
  ["BE020","Consommation finale de produits raffinés dans le transport (hors biocarburants)","Pétrole","Mtep","Métropole","Réelles","Transport"],
  ["BE021","Consommation finale de produits raffinés dans le tertiaire","Pétrole","Mtep","Métropole","Réelles","Tertiaire"],
  ["BE022","Consommation finale de produits raffinés dans le résidentiel","Pétrole","Mtep","Métropole","Réelles","Résidentiel"],
  ["BE023","Consommation finale de produits raffinés dans l'agriculture","Pétrole","Mtep","Métropole","Réelles","Agriculture"],
  ["BE024","Consommation finale à usage non énergétique de produits raffinés","Pétrole","Mtep","Métropole","Réelles","Usages non énergétiques"],
  ["BE025","Consommation finale de produits raffinés, tous usages confondus","Pétrole","Mtep","Métropole","Réelles","Consommation finale"],
  ["BE026","Consommation nette de pétrole (brut et raffinés) de la branche énergie (y compris écart statistique et transferts)","Pétrole","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE027","Consommation totale brute de produits raffinés (hors écart statistique et transferts)","Pétrole","Mtep","Métropole","Réelles","Consommation totale"],
  ["BE028","Consommation primaire de pétrole (Total brut et raffinés)","Pétrole","Mtep","Métropole","CVC","Consommation primaire"],
  ["BE029","Consommation finale à usage énergétique de produits raffinés","Pétrole","Mtep","Métropole","CVC","Consommation finale énergétique"],
  ["BE030","Consommation finale de produits raffinés dans l'industrie","Pétrole","Mtep","Métropole","CVC","Industrie"],
  ["BE031","Consommation finale de produits raffinés dans le tertiaire","Pétrole","Mtep","Métropole","CVC","Tertiaire"],
  ["BE032","Consommation finale de produits raffinés dans le résidentiel","Pétrole","Mtep","Métropole","CVC","Résidentiel"],
  ["BE033","Consommation finale de produits raffinés, tous usages confondus","Pétrole","Mtep","Métropole","CVC","Consommation finale"],
  ["BE034","Consommation totale brute de produits raffinés (hors écart statistique et transferts)","Pétrole","Mtep","Métropole","CVC","Consommation totale"],
  ["BE035","Production de pétrole brut","Pétrole","kilotonne","Métropole","Réelles","Production primaire"],
  ["BE036","Importations de pétrole brut","Pétrole","kilotonne","Métropole","Réelles","Importations"],
  ["BE037","Exportations de pétrole brut","Pétrole","kilotonne","Métropole","Réelles","Exportations"],
  ["BE038","Variations de stocks de pétrole brut (stocks au 1er janvier N - stocks au 31 décembre N)","Pétrole","kilotonne","Métropole","Réelles","Stocks"],
  ["BE039","Disponibilités (Consommation primaire) en pétrole brut","Pétrole","kilotonne","Métropole","Réelles","Consommation primaire"],
  ["BE040","Importations de produits raffinés","Pétrole","kilotonne","Métropole","Réelles","Importations"],
  ["BE041","Exportations de produits raffinés","Pétrole","kilotonne","Métropole","Réelles","Exportations"],
  ["BE042","Variations de stocks de produits raffinés (stocks au 1er janvier N - stocks au 31 décembre N)","Pétrole","kilotonne","Métropole","Réelles","Stocks"],
  ["BE043","Soutes maritimes internationales (produits raffinés)","Pétrole","kilotonne","Métropole","Réelles","Soutes"],
  ["BE044","Soutes aériennes internationales (produits raffinés)","Pétrole","kilotonne","Métropole","Réelles","Soutes"],
  ["BE045","Consommation primaire de pétrole (Total brut et raffinés)","Pétrole","kilotonne","Métropole","Réelles","Consommation primaire"],
  ["BE046","Consommation de pétrole brut des raffineries","Pétrole","kilotonne","Métropole","Réelles","Branche énergie"],
  ["BE047","Consommation de produits raffinés pour la production d'électricité seule","Pétrole","kilotonne","Métropole","Réelles","Branche énergie"],
  ["BE048","Consommation de produits raffinés pour la cogénération","Pétrole","kilotonne","Métropole","Réelles","Branche énergie"],
  ["BE049","Consommation de produits raffinés pour la production de chaleur seule","Pétrole","kilotonne","Métropole","Réelles","Branche énergie"],
  ["BE050","Production brute des raffineries en produits raffinés","Pétrole","kilotonne","Métropole","Réelles","Branche énergie"],
  ["BE051","Autoconsommation des raffineries en produits raffinés (hors production d'électricité et chaleur)","Pétrole","kilotonne","Métropole","Réelles","Branche énergie"],
  ["BE052","Consommation finale à usage énergétique de produits raffinés","Pétrole","kilotonne","Métropole","Réelles","Consommation finale énergétique"],
  ["BE053","Consommation finale de produits raffinés dans l'industrie","Pétrole","kilotonne","Métropole","Réelles","Industrie"],
  ["BE054","Consommation finale de produits raffinés dans le transport (hors biocarburants)","Pétrole","kilotonne","Métropole","Réelles","Transport"],
  ["BE055","Consommation finale de produits raffinés dans le tertiaire","Pétrole","kilotonne","Métropole","Réelles","Tertiaire"],
  ["BE056","Consommation finale de produits raffinés dans le résidentiel","Pétrole","kilotonne","Métropole","Réelles","Résidentiel"],
  ["BE057","Consommation finale de produits raffinés dans l'agriculture","Pétrole","kilotonne","Métropole","Réelles","Agriculture"],
  ["BE058","Consommation finale à usage non énergétique de produits raffinés","Pétrole","kilotonne","Métropole","Réelles","Usages non énergétiques"],
  ["BE059","Consommation finale de produits raffinés, tous usages confondus","Pétrole","kilotonne","Métropole","Réelles","Consommation finale"],
  ["BE060","Consommation nette de pétrole (brut et raffinés) de la branche énergie (y compris écart statistique et transferts)","Pétrole","kilotonne","Métropole","Réelles","Branche énergie"],
  ["BE061","Consommation totale brute de produits raffinés (hors écart statistique et transferts)","Pétrole","kilotonne","Métropole","Réelles","Consommation totale"],
  ["BE062","Consommation primaire de pétrole (Total brut et raffinés)","Pétrole","kilotonne","Métropole","CVC","Consommation primaire"],
  ["BE063","Consommation finale à usage énergétique de produits raffinés","Pétrole","kilotonne","Métropole","CVC","Consommation finale énergétique"],
  ["BE064","Consommation finale de produits raffinés dans l'industrie","Pétrole","kilotonne","Métropole","CVC","Industrie"],
  ["BE065","Consommation finale de produits raffinés dans le tertiaire","Pétrole","kilotonne","Métropole","CVC","Tertiaire"],
  ["BE066","Consommation finale de produits raffinés dans le résidentiel","Pétrole","kilotonne","Métropole","CVC","Résidentiel"],
  ["BE067","Consommation finale de produits raffinés, tous usages confondus","Pétrole","kilotonne","Métropole","CVC","Consommation finale"],
  ["BE068","Consommation totale brute de produits raffinés (hors écart statistique et transferts)","Pétrole","kilotonne","Métropole","CVC","Consommation totale"],
  ["BE069","Importations de pétrole brut d'Arabie Saoudite","Pétrole","kilotonne","Métropole","Réelles","Importations"],
  ["BE070","Importations de pétrole brut du Kazakhstan","Pétrole","kilotonne","Métropole","Réelles","Importations"],
  ["BE071","Importations de pétrole brut de Russie","Pétrole","kilotonne","Métropole","Réelles","Importations"],
  ["BE072","Importations de pétrole brut de Norvège","Pétrole","kilotonne","Métropole","Réelles","Importations"],
  ["BE073","Importations de pétrole brut d'Iran","Pétrole","kilotonne","Métropole","Réelles","Importations"],
  ["BE074","Importations de pétrole brut d'Algérie","Pétrole","kilotonne","Métropole","Réelles","Importations"],
  ["BE075","Importations de pétrole brut d'Angola","Pétrole","kilotonne","Métropole","Réelles","Importations"],
  ["BE076","Importations de pétrole brut d'Azerbaïdjan","Pétrole","kilotonne","Métropole","Réelles","Importations"],
  ["BE077","Importations de pétrole brut de Libye","Pétrole","kilotonne","Métropole","Réelles","Importations"],
  ["BE078","Importations de pétrole brut du Royaume-Uni","Pétrole","kilotonne","Métropole","Réelles","Importations"],
  ["BE079","Importations de pétrole brut du Mexique","Pétrole","kilotonne","Métropole","Réelles","Importations"],
  ["BE080","Importations de pétrole brut d'Irak","Pétrole","kilotonne","Métropole","Réelles","Importations"],
  ["BE081","Production de charbon primaire","Charbon","Mtep","Métropole","Réelles","Production primaire"],
  ["BE082","Importations de charbon primaire (nettes des exportations depuis 2011)","Charbon","Mtep","Métropole","Réelles","Importations"],
  ["BE083","Exportations de charbon primaire","Charbon","Mtep","Métropole","Réelles","Exportations"],
  ["BE084","Variations de stocks de charbon primaire (stocks au 1er janvier N - stocks au 31 décembre N)","Charbon","Mtep","Métropole","Réelles","Stocks"],
  ["BE085","Disponibilités (Consommation primaire) en charbon primaire","Charbon","Mtep","Métropole","Réelles","Consommation primaire"],
  ["BE086","Importations de charbon dérivé","Charbon","Mtep","Métropole","Réelles","Importations"],
  ["BE087","Exportations de charbon dérivé","Charbon","Mtep","Métropole","Réelles","Exportations"],
  ["BE088","Variations de stocks de charbon dérivé (stocks au 1er janvier N - stocks au 31 décembre N)","Charbon","Mtep","Métropole","Réelles","Stocks"],
  ["BE089","Consommation primaire de charbon (tous produits confondus)","Charbon","Mtep","Métropole","Réelles","Consommation primaire"],
  ["BE090","Consommation de charbon pour la production d'électricité seule (charbon-vapeur et gaz dérivés)","Charbon","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE091","Consommation de charbon pour la cogénération (charbon-vapeur et gaz dérivés)","Charbon","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE092","Consommation de charbon pour la production de chaleur seule (charbon-vapeur et gaz dérivés)","Charbon","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE093","Consommation de charbon primaire dans les cokeries (charbon à coke)","Charbon","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE094","Consommation de charbon dérivé dans les cokeries","Charbon","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE095","Consommation brute de gaz dérivés dans les cokeries","Charbon","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE096","Production de charbon dérivé (coke) dans les cokeries","Charbon","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE097","Production brute de gaz dérivés dans les cokeries","Charbon","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE098","Consommation nette de charbon dans les cokeries (tous produits confondus)","Charbon","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE099","Consommation de charbon primaire dans les hauts-fourneaux","Charbon","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE100","Consommation de charbon dérivé (coke) dans les hauts-fourneaux","Charbon","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE101","Consommation brute de gaz dérivés dans les hauts-fourneaux","Charbon","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE102","Production brute de gaz dérivés dans les hauts-fourneaux","Charbon","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE103","Consommation nette de charbon dans les hauts-fourneaux (tous produits confondus)","Charbon","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE104","Consommation nette de charbon de la filière fonte (tous produits confondus)","Charbon","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE105","Consommation nette de charbon de la branche énergie (tous produits confondus, y compris écart statistique)","Charbon","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE106","Consommation finale à usage énergétique de charbon","Charbon","Mtep","Métropole","Réelles","Consommation finale énergétique"],
  ["BE107","Consommation finale de charbon dans l'industrie","Charbon","Mtep","Métropole","Réelles","Industrie"],
  ["BE108","Consommation finale de charbon dans le transport","Charbon","Mtep","Métropole","Réelles","Transport"],
  ["BE109","Consommation finale de charbon dans le tertiaire (y.c. consommation finale non affectée à un secteur)","Charbon","Mtep","Métropole","Réelles","Tertiaire"],
  ["BE110","Consommation finale de charbon dans le résidentiel","Charbon","Mtep","Métropole","Réelles","Résidentiel"],
  ["BE111","Consommation finale de charbon dans l'agriculture","Charbon","Mtep","Métropole","Réelles","Agriculture"],
  ["BE112","Consommation finale à usage non énergétique de charbon","Charbon","Mtep","Métropole","Réelles","Usages non énergétiques"],
  ["BE113","Consommation finale de charbon, tous usages confondus","Charbon","Mtep","Métropole","Réelles","Consommation finale"],
  ["BE114","Consommation primaire de charbon (tous produits confondus)","Charbon","Mtep","Métropole","CVC","Consommation primaire"],
  ["BE115","Consommation de charbon pour la production d'électricité et de chaleur (charbon-vapeur et gaz dérivés)","Charbon","Mtep","Métropole","CVC","Branche énergie"],
  ["BE116","Consommation nette de charbon de la branche énergie (tous produits confondus, y compris écart statistique)","Charbon","Mtep","Métropole","CVC","Branche énergie"],
  ["BE117","Consommation finale à usage énergétique de charbon","Charbon","Mtep","Métropole","CVC","Consommation finale énergétique"],
  ["BE118","Consommation finale de charbon dans le résidentiel","Charbon","Mtep","Métropole","CVC","Résidentiel"],
  ["BE119","Consommation finale de charbon, tous usages confondus","Charbon","Mtep","Métropole","CVC","Consommation finale"],
  ["BE120","Production de charbon primaire","Charbon","kilotonne","Métropole","Réelles","Production primaire"],
  ["BE121","Importations de charbon primaire (nettes des exportations depuis 2011)","Charbon","kilotonne","Métropole","Réelles","Importations"],
  ["BE122","Exportations de charbon primaire","Charbon","kilotonne","Métropole","Réelles","Exportations"],
  ["BE123","Variations de stocks de charbon primaire (stocks au 1er janvier N - stocks au 31 décembre N)","Charbon","kilotonne","Métropole","Réelles","Stocks"],
  ["BE124","Disponibilités (Consommation primaire) en charbon primaire","Charbon","kilotonne","Métropole","Réelles","Consommation primaire"],
  ["BE125","Importations de charbon dérivé","Charbon","kilotonne","Métropole","Réelles","Importations"],
  ["BE126","Exportations de charbon dérivé","Charbon","kilotonne","Métropole","Réelles","Exportations"],
  ["BE127","Variations de stocks de charbon dérivé (stocks au 1er janvier N - stocks au 31 décembre N)","Charbon","kilotonne","Métropole","Réelles","Stocks"],
  ["BE128","Consommation primaire de charbon (tous produits confondus)","Charbon","kilotonne","Métropole","Réelles","Consommation primaire"],
  ["BE129","Importations de charbon (primaire et dérivé) d'Afrique du Sud","Charbon","kilotonne","Métropole","Réelles","Importations"],
  ["BE130","Importations de charbon (primaire et dérivé) d'Allemagne","Charbon","kilotonne","Métropole","Réelles","Importations"],
  ["BE131","Importations de charbon (primaire et dérivé) d'Australie","Charbon","kilotonne","Métropole","Réelles","Importations"],
  ["BE132","Importations de charbon (primaire et dérivé) de Colombie","Charbon","kilotonne","Métropole","Réelles","Importations"],
  ["BE133","Importations de charbon (primaire et dérivé) des États-Unis","Charbon","kilotonne","Métropole","Réelles","Importations"],
  ["BE134","Importations de charbon (primaire et dérivé) de la Fédération de Russie","Charbon","kilotonne","Métropole","Réelles","Importations"],
  ["BE135","Importations de charbon (primaire et dérivé) de Pologne","Charbon","kilotonne","Métropole","Réelles","Importations"],
  ["BE136","Production de charbon primaire, en valeur","Charbon","M€ courants","Métropole","Réelles","Production primaire"],
  ["BE137","Importations de charbon (tous produits confondus), en valeur","Charbon","M€ courants","Métropole","Réelles","Importations"],
  ["BE138","Exportations de charbon (tous produits confondus), en valeur","Charbon","M€ courants","Métropole","Réelles","Exportations"],
  ["BE139","Variations de stocks de charbon (tous produits confondus, déstockage positif), en valeur","Charbon","M€ courants","Métropole","Réelles","Stocks"],
  ["BE140","Marges de cokéfaction (charbon), en valeur","Charbon","M€ courants","Métropole","Réelles","Marges, Taxes, Subventions"],
  ["BE141","Marges (hors marges de cokéfaction) et écart statistique (charbon), en valeur","Charbon","M€ courants","Métropole","Réelles","Marges, Taxes, Subventions"],
  ["BE142","Taxe sur la valeur ajoutée (TVA) sur la consommation de charbon","Charbon","M€ courants","Métropole","Réelles","Marges, Taxes, Subventions"],
  ["BE143","Taxe intérieure de consommation sur le charbon (TICC)","Charbon","M€ courants","Métropole","Réelles","Marges, Taxes, Subventions"],
  ["BE144","Dépense totale en charbon (TVA incluse pour résidentiel seulement)","Charbon","M€ courants","Métropole","Réelles","Consommation totale"],
  ["BE145","Dépense en charbon pour la production d’électricité et de chaleur (HTVA)","Charbon","M€ courants","Métropole","Réelles","Branche énergie"],
  ["BE146","Dépense en charbon des hauts-fourneaux (HTVA)","Charbon","M€ courants","Métropole","Réelles","Branche énergie"],
  ["BE147","Dépense en charbon dans l'industrie (HTVA)","Charbon","M€ courants","Métropole","Réelles","Industrie"],
  ["BE148","Dépense en charbon pour usages finaux énergétiques non industriels (TVA incluse pour résidentiel seulement)","Charbon","M€ courants","Métropole","Réelles","Consommation finale énergétique"],
  ["BE149","Dépense en charbon pour usages non-énergétiques (HTVA)","Charbon","M€ courants","Métropole","Réelles","Usages non énergétiques"],
  ["BE150","Production nationale de gaz naturel (biométhane exclu)","Gaz naturel","Mtep (PCI)","Métropole","Réelles","Production primaire"],
  ["BE151","Importations de gaz naturel","Gaz naturel","Mtep (PCI)","Métropole","Réelles","Importations"],
  ["BE152","Importations de gaz naturel gazeux","Gaz naturel","Mtep (PCI)","Métropole","Réelles","Importations"],
  ["BE153","Importations de gaz naturel liquéfié","Gaz naturel","Mtep (PCI)","Métropole","Réelles","Importations"],
  ["BE154","Exportations de gaz naturel","Gaz naturel","Mtep (PCI)","Métropole","Réelles","Exportations"],
  ["BE155","Variations de stocks de gaz naturel (stocks au 1er janvier N - stocks au 31 décembre N)","Gaz naturel","Mtep (PCI)","Métropole","Réelles","Stocks"],
  ["BE156","Consommation primaire de gaz naturel","Gaz naturel","Mtep (PCI)","Métropole","Réelles","Consommation primaire"],
  ["BE157","Pertes de transport et de distribution du gaz naturel","Gaz naturel","Mtep (PCI)","Métropole","Réelles","Branche énergie"],
  ["BE158","Consommation nette de gaz naturel de la branche énergie (y compris pertes et écart statistique)","Gaz naturel","Mtep (PCI)","Métropole","Réelles","Branche énergie"],
  ["BE159","Consommation de gaz naturel pour la production d'électricité seule","Gaz naturel","Mtep (PCI)","Métropole","Réelles","Branche énergie"],
  ["BE160","Consommation de gaz naturel pour la cogénération","Gaz naturel","Mtep (PCI)","Métropole","Réelles","Branche énergie"],
  ["BE161","Consommation de gaz naturel pour la production de chaleur seule","Gaz naturel","Mtep (PCI)","Métropole","Réelles","Branche énergie"],
  ["BE162","Injections de biométhane dans les réseaux de gaz naturel","Gaz naturel","Mtep (PCI)","Métropole","Réelles","Branche énergie"],
  ["BE163","Usages internes de la branche énergie en gaz naturel","Gaz naturel","Mtep (PCI)","Métropole","Réelles","Branche énergie"],
  ["BE164","Consommation finale à usage énergétique de gaz naturel","Gaz naturel","Mtep (PCI)","Métropole","Réelles","Consommation finale énergétique"],
  ["BE165","Consommation finale de gaz naturel dans l'industrie","Gaz naturel","Mtep (PCI)","Métropole","Réelles","Industrie"],
  ["BE166","Consommation finale de gaz naturel dans le transport","Gaz naturel","Mtep (PCI)","Métropole","Réelles","Transport"],
  ["BE167","Consommation finale de gaz naturel dans le tertiaire","Gaz naturel","Mtep (PCI)","Métropole","Réelles","Tertiaire"],
  ["BE168","Consommation finale de gaz naturel dans le résidentiel","Gaz naturel","Mtep (PCI)","Métropole","Réelles","Résidentiel"],
  ["BE169","Consommation finale de gaz naturel dans le résidentiel-tertiaire","Gaz naturel","Mtep (PCI)","Métropole","Réelles","Résidentiel-Tertiaire"],
  ["BE170","Consommation finale de gaz naturel dans l'agriculture","Gaz naturel","Mtep (PCI)","Métropole","Réelles","Agriculture"],
  ["BE171","Consommation finale de gaz naturel à usage non énergétique","Gaz naturel","Mtep (PCI)","Métropole","Réelles","Usages non énergétiques"],
  ["BE172","Consommation finale de gaz naturel, tous usages confondus","Gaz naturel","Mtep (PCI)","Métropole","Réelles","Consommation finale"],
  ["BE173","Consommation primaire de gaz naturel","Gaz naturel","Mtep (PCI)","Métropole","CVC","Consommation primaire"],
  ["BE174","Pertes de transport et de distribution du gaz naturel","Gaz naturel","Mtep (PCI)","Métropole","CVC","Branche énergie"],
  ["BE175","Consommation nette de gaz naturel de la branche énergie (y compris pertes et écart statistique)","Gaz naturel","Mtep (PCI)","Métropole","CVC","Branche énergie"],
  ["BE176","Consommation de gaz naturel pour la production d'électricité seule","Gaz naturel","Mtep (PCI)","Métropole","CVC","Branche énergie"],
  ["BE177","Consommation de gaz naturel pour la cogénération","Gaz naturel","Mtep (PCI)","Métropole","CVC","Branche énergie"],
  ["BE178","Consommation de gaz naturel pour la production de chaleur seule","Gaz naturel","Mtep (PCI)","Métropole","CVC","Branche énergie"],
  ["BE179","Consommation finale à usage énergétique de gaz naturel","Gaz naturel","Mtep (PCI)","Métropole","CVC","Consommation finale énergétique"],
  ["BE180","Consommation finale de gaz naturel dans l'industrie","Gaz naturel","Mtep (PCI)","Métropole","CVC","Industrie"],
  ["BE181","Consommation finale de gaz naturel dans le tertiaire","Gaz naturel","Mtep (PCI)","Métropole","CVC","Tertiaire"],
  ["BE182","Consommation finale de gaz naturel dans le résidentiel","Gaz naturel","Mtep (PCI)","Métropole","CVC","Résidentiel"],
  ["BE183","Consommation finale de gaz naturel dans le résidentiel-tertiaire","Gaz naturel","Mtep (PCI)","Métropole","CVC","Résidentiel-Tertiaire"],
  ["BE184","Consommation finale de gaz naturel, tous usages confondus","Gaz naturel","Mtep (PCI)","Métropole","CVC","Consommation finale"],
  ["BE185","Production nationale de gaz naturel (biométhane exclu)","Gaz naturel","TWh (PCS)","Métropole","Réelles","Production primaire"],
  ["BE186","Importations de gaz naturel","Gaz naturel","TWh (PCS)","Métropole","Réelles","Importations"],
  ["BE187","Importations de gaz naturel gazeux","Gaz naturel","TWh (PCS)","Métropole","Réelles","Importations"],
  ["BE188","Importations de gaz naturel liquéfié","Gaz naturel","TWh (PCS)","Métropole","Réelles","Importations"],
  ["BE189","Exportations de gaz naturel","Gaz naturel","TWh (PCS)","Métropole","Réelles","Exportations"],
  ["BE190","Variations de stocks de gaz naturel (stocks au 1er janvier N - stocks au 31 décembre N)","Gaz naturel","TWh (PCS)","Métropole","Réelles","Stocks"],
  ["BE191","Consommation primaire de gaz naturel","Gaz naturel","TWh (PCS)","Métropole","Réelles","Consommation primaire"],
  ["BE192","Pertes de transport et de distribution du gaz naturel","Gaz naturel","TWh (PCS)","Métropole","Réelles","Branche énergie"],
  ["BE193","Consommation nette de gaz naturel de la branche énergie (y compris pertes et écart statistique)","Gaz naturel","TWh (PCS)","Métropole","Réelles","Branche énergie"],
  ["BE194","Consommation de gaz naturel pour la production d'électricité seule","Gaz naturel","TWh (PCS)","Métropole","Réelles","Branche énergie"],
  ["BE195","Consommation de gaz naturel pour la cogénération","Gaz naturel","TWh (PCS)","Métropole","Réelles","Branche énergie"],
  ["BE196","Consommation de gaz naturel pour la production de chaleur seule","Gaz naturel","TWh (PCS)","Métropole","Réelles","Branche énergie"],
  ["BE197","Injections de biométhane dans les réseaux de gaz naturel","Gaz naturel","TWh (PCS)","Métropole","Réelles","Branche énergie"],
  ["BE198","Usages internes de la branche énergie en gaz naturel","Gaz naturel","TWh (PCS)","Métropole","Réelles","Branche énergie"],
  ["BE199","Consommation finale à usage énergétique de gaz naturel","Gaz naturel","TWh (PCS)","Métropole","Réelles","Consommation finale énergétique"],
  ["BE200","Consommation finale de gaz naturel dans l'industrie","Gaz naturel","TWh (PCS)","Métropole","Réelles","Industrie"],
  ["BE201","Consommation finale de gaz naturel dans le transport","Gaz naturel","TWh (PCS)","Métropole","Réelles","Transport"],
  ["BE202","Consommation finale de gaz naturel dans le tertiaire","Gaz naturel","TWh (PCS)","Métropole","Réelles","Tertiaire"],
  ["BE203","Consommation finale de gaz naturel dans le résidentiel","Gaz naturel","TWh (PCS)","Métropole","Réelles","Résidentiel"],
  ["BE204","Consommation finale de gaz naturel dans le résidentiel-tertiaire","Gaz naturel","TWh (PCS)","Métropole","Réelles","Résidentiel-tertiaire"],
  ["BE205","Consommation finale de gaz naturel dans l'agriculture","Gaz naturel","TWh (PCS)","Métropole","Réelles","Agriculture"],
  ["BE206","Consommation finale de gaz naturel à usage non énergétique","Gaz naturel","TWh (PCS)","Métropole","Réelles","Usages non énergétiques"],
  ["BE207","Consommation finale de gaz naturel, tous usages confondus","Gaz naturel","TWh (PCS)","Métropole","Réelles","Consommation finale"],
  ["BE208","Consommation primaire de gaz naturel","Gaz naturel","TWh (PCS)","Métropole","CVC","Consommation primaire"],
  ["BE209","Pertes de transport et de distribution du gaz naturel","Gaz naturel","TWh (PCS)","Métropole","CVC","Branche énergie"],
  ["BE210","Consommation nette de gaz naturel de la branche énergie (y compris pertes et écart statistique)","Gaz naturel","TWh (PCS)","Métropole","CVC","Branche énergie"],
  ["BE211","Consommation de gaz naturel pour la production d'électricité seule","Gaz naturel","TWh (PCS)","Métropole","CVC","Branche énergie"],
  ["BE212","Consommation de gaz naturel pour la cogénération","Gaz naturel","TWh (PCS)","Métropole","CVC","Branche énergie"],
  ["BE213","Consommation de gaz naturel pour la production de chaleur seule","Gaz naturel","TWh (PCS)","Métropole","CVC","Branche énergie"],
  ["BE214","Consommation finale à usage énergétique de gaz naturel","Gaz naturel","TWh (PCS)","Métropole","CVC","Consommation finale énergétique"],
  ["BE215","Consommation finale de gaz naturel dans l'industrie","Gaz naturel","TWh (PCS)","Métropole","CVC","Industrie"],
  ["BE216","Consommation finale de gaz naturel dans le tertiaire","Gaz naturel","TWh (PCS)","Métropole","CVC","Tertiaire"],
  ["BE217","Consommation finale de gaz naturel dans le résidentiel","Gaz naturel","TWh (PCS)","Métropole","CVC","Résidentiel"],
  ["BE218","Consommation finale de gaz naturel dans le résidentiel-tertiaire","Gaz naturel","TWh (PCS)","Métropole","CVC","Résidentiel-tertiaire"],
  ["BE219","Consommation finale de gaz naturel, tous usages confondus","Gaz naturel","TWh (PCS)","Métropole","CVC","Consommation finale"],
  ["BE220","Importations de gaz naturel de Norvège","Gaz naturel","TWh (PCS)","Métropole","Réelles","Importations"],
  ["BE221","Importations de gaz naturel de Russie","Gaz naturel","TWh (PCS)","Métropole","Réelles","Importations"],
  ["BE222","Importations de gaz naturel d'Algérie","Gaz naturel","TWh (PCS)","Métropole","Réelles","Importations"],
  ["BE223","Importations de gaz naturel des Pays-Bas","Gaz naturel","TWh (PCS)","Métropole","Réelles","Importations"],
  ["BE224","Importations de gaz naturel du Nigeria (yc swaps)","Gaz naturel","TWh (PCS)","Métropole","Réelles","Importations"],
  ["BE225","Importations de gaz naturel du Qatar","Gaz naturel","TWh (PCS)","Métropole","Réelles","Importations"],
  ["BE226","Production nationale de gaz naturel (biométhane exclu), en valeur","Gaz naturel","M€ courants","Métropole","Réelles","Production primaire"],
  ["BE227","Importations de gaz naturel, en valeur","Gaz naturel","M€ courants","Métropole","Réelles","Importations"],
  ["BE228","Importations de gaz naturel gazeux, en valeur","Gaz naturel","M€ courants","Métropole","Réelles","Importations"],
  ["BE229","Importations de gaz naturel liquéfié, en valeur","Gaz naturel","M€ courants","Métropole","Réelles","Importations"],
  ["BE230","Exportations de gaz naturel, en valeur","Gaz naturel","M€ courants","Métropole","Réelles","Exportations"],
  ["BE231","Variations de stocks de gaz naturel (déstockage positif), en valeur","Gaz naturel","M€ courants","Métropole","Réelles","Stocks"],
  ["BE232","Utilisation des infrastructures gazières (hors pertes), en valeur","Gaz naturel","M€ courants","Métropole","Réelles","Branche énergie"],
  ["BE233","Pertes de transport et de distribution du gaz naturel, en valeur","Gaz naturel","M€ courants","Métropole","Réelles","Branche énergie"],
  ["BE234","Marges et écart statistique (gaz naturel), en valeur","Gaz naturel","M€ courants","Métropole","Réelles","Marges, Taxes, Subventions"],
  ["BE235","Taxes sur le gaz naturel (toutes taxes, y compris TVA)","Gaz naturel","M€ courants","Métropole","Réelles","Marges, Taxes, Subventions"],
  ["BE236","Subventions pour le gaz naturel (tarifs sociaux, obligations d'achat biométhane)","Gaz naturel","M€ courants","Métropole","Réelles","Marges, Taxes, Subventions"],
  ["BE237","Dépense totale en gaz naturel (TVA incluse pour résidentiel seulement)","Gaz naturel","M€ courants","Métropole","Réelles","Consommation totale"],
  ["BE238","Dépense en gaz naturel dans la branche énergie (HTVA)","Gaz naturel","M€ courants","Métropole","Réelles","Branche énergie"],
  ["BE239","Dépense en gaz naturel pour la production d'électricité et de chaleur (HTVA)","Gaz naturel","M€ courants","Métropole","Réelles","Branche énergie"],
  ["BE240","Dépense en gaz naturel dans la branche énergie (hors branche électricité et chaleur) (HTVA)","Gaz naturel","M€ courants","Métropole","Réelles","Branche énergie"],
  ["BE241","Dépense en gaz naturel pour usages finaux énergétiques (TVA incluse pour résidentiel seulement)","Gaz naturel","M€ courants","Métropole","Réelles","Consommation finale énergétique"],
  ["BE242","Dépense en gaz naturel dans l'industrie (HTVA)","Gaz naturel","M€ courants","Métropole","Réelles","Industrie"],
  ["BE243","Dépense en gaz naturel dans le tertiaire et le transport (HTVA)","Gaz naturel","M€ courants","Métropole","Réelles","Tertiaire"],
  ["BE244","Dépense en gaz naturel dans le résidentiel (TTC)","Gaz naturel","M€ courants","Métropole","Réelles","Résidentiel"],
  ["BE245","Dépense en gaz naturel dans l'agriculture (HTVA)","Gaz naturel","M€ courants","Métropole","Réelles","Agriculture"],
  ["BE246","Dépense en gaz naturel pour usages non énergétiques (HTVA)","Gaz naturel","M€ courants","Métropole","Réelles","Usages non énergétiques"],
  ["BE247","Production nucléaire (chaleur issue de la réaction nucléaire)","Nucléaire","Mtep","Métropole","Réelles","Production primaire"],
  ["BE248","Consommation primaire d'énergie nucléaire, déduction faite du solde exportateur d'électricité","Nucléaire","Mtep","Métropole","Réelles","Consommation primaire"],
  ["BE249","Consommation primaire d'énergie nucléaire, déduction faite du solde exportateur d'électricité","Nucléaire","Mtep","Métropole","CVC","Consommation primaire"],
  ["BE250","Importations d'électricité","Électricité","TWh","Métropole","Réelles","Importations"],
  ["BE251","Exportations d'électricité","Électricité","TWh","Métropole","Réelles","Exportations"],
  ["BE252","Production brute d'électricité","Électricité","TWh","Métropole","Réelles","Branche énergie"],
  ["BE253","Production brute d'électricité nucléaire","Électricité","TWh","Métropole","Réelles","Branche énergie"],
  ["BE254","Production brute d'électricité hydraulique (y compris pompages)","Électricité","TWh","Métropole","Réelles","Branche énergie"],
  ["BE255","Production brute d'électricité géothermique","Électricité","TWh","Métropole","Réelles","Branche énergie"],
  ["BE256","Production brute d'électricité solaire photovoltaïque","Électricité","TWh","Métropole","Réelles","Production primaire"],
  ["BE257","Production brute d'électricité issue des énergies marines","Électricité","TWh","Métropole","Réelles","Production primaire"],
  ["BE258","Production brute d'électricité éolienne","Électricité","TWh","Métropole","Réelles","Production primaire"],
  ["BE259","Production brute d'électricité des centrales thermiques classiques","Électricité","TWh","Métropole","Réelles","Branche énergie"],
  ["BE260","Production brute d'électricité, autres sources","Électricité","TWh","Métropole","Réelles","Branche énergie"],
  ["BE261","Production brute d'électricité hydraulique (hors pompages)","Électricité","TWh","Métropole","Réelles","Production primaire"],
  ["BE262","Production brute d'électricité hydraulique des stations de pompages (STEP)","Électricité","TWh","Métropole","Réelles","Branche énergie"],
  ["BE263","Consommation propre des centrales électriques","Électricité","TWh","Métropole","Réelles","Branche énergie"],
  ["BE264","Production nette d'électricité","Électricité","TWh","Métropole","Réelles","Branche énergie"],
  ["BE265","Production nette d'électricité nucléaire","Électricité","TWh","Métropole","Réelles","Branche énergie"],
  ["BE266","Production nette d'électricité hydraulique (y compris pompages)","Électricité","TWh","Métropole","Réelles","Branche énergie"],
  ["BE267","Production nette d'électricité géothermique","Électricité","TWh","Métropole","Réelles","Branche énergie"],
  ["BE268","Production nette d'électricité solaire photovoltaïque","Électricité","TWh","Métropole","Réelles","Production primaire"],
  ["BE269","Production nette d'électricité issue des énergies marines","Électricité","TWh","Métropole","Réelles","Production primaire"],
  ["BE270","Production nette d'électricité éolienne","Électricité","TWh","Métropole","Réelles","Production primaire"],
  ["BE271","Production nette d'électricité des centrales thermiques classiques","Électricité","TWh","Métropole","Réelles","Branche énergie"],
  ["BE272","Production nette d'électricité, autres sources","Électricité","TWh","Métropole","Réelles","Branche énergie"],
  ["BE273","Production nette d'électricité hydraulique (hors pompages)","Électricité","TWh","Métropole","Réelles","Production primaire"],
  ["BE274","Production nette d'électricité hydraulique des stations de pompages (STEP)","Électricité","TWh","Métropole","Réelles","Branche énergie"],
  ["BE275","Production nette d'électricité nucléaire vendue dans le cadre de l'Arenh","Électricité","TWh","France continentale","Réelles","Branche énergie"],
  ["BE276","Production nette d'électricité sous obligation d'achat","Électricité","TWh","France continentale","Réelles","Branche énergie"],
  ["BE277","Production nette d'électricité hydraulique sous obligation d'achat","Électricité","TWh","France continentale","Réelles","Production primaire"],
  ["BE278","Production nette d'électricité éolienne sous obligation d'achat","Électricité","TWh","France continentale","Réelles","Production primaire"],
  ["BE279","Production nette d'électricité solaire photovoltaïque sous obligation d'achat","Électricité","TWh","France continentale","Réelles","Production primaire"],
  ["BE280","Production nette d'électricité des centrales thermiques classiques sous obligation d'achat","Électricité","TWh","France continentale","Réelles","Branche énergie"],
  ["BE281","Production nette d'électricité dans les zones non interconnectées","Électricité","TWh","Zones non interconnectées","Réelles","Branche énergie"],
  ["BE282","Énergie absorbée par le pompage","Électricité","TWh","Métropole","Réelles","Branche énergie"],
  ["BE283","Pertes de transport et de distribution d'électricité","Électricité","TWh","Métropole","Réelles","Branche énergie"],
  ["BE284","Usages internes de la branche énergie en électricité (hors pertes, consommation propre des centrales et énergie absorbée par le pompage)","Électricité","TWh","Métropole","Réelles","Branche énergie"],
  ["BE285","Consommation nette d'électricité de la branche énergie (y compris pertes et écart statistique)","Électricité","TWh","Métropole","Réelles","Branche énergie"],
  ["BE286","Consommation finale à usage énergétique d'électricité","Électricité","TWh","Métropole","Réelles","Consommation finale énergétique"],
  ["BE287","Consommation finale d'électricité dans l'industrie","Électricité","TWh","Métropole","Réelles","Industrie"],
  ["BE288","Consommation finale d'électricité dans le transport","Électricité","TWh","Métropole","Réelles","Transport"],
  ["BE289","Consommation finale d'électricité dans le tertiaire","Électricité","TWh","Métropole","Réelles","Tertiaire"],
  ["BE290","Consommation finale d'électricité dans le résidentiel","Électricité","TWh","Métropole","Réelles","Résidentiel"],
  ["BE291","Consommation finale d'électricité dans l'agriculture","Électricité","TWh","Métropole","Réelles","Agriculture"],
  ["BE292","Consommation finale d'électricité, tous usages confondus","Électricité","TWh","Métropole","Réelles","Consommation finale"],
  ["BE293","Consommation totale d'électricité (y compris écart statistique), déduction faite des pertes, de la consommation propre des centrales et de l'énergie absorbée par le pompage","Électricité","TWh","Métropole","Réelles","Consommation totale"],
  ["BE294","Pertes de transport et de distribution d'électricité","Électricité","TWh","Métropole","CVC","Branche énergie"],
  ["BE295","Consommation nette d'électricité de la branche énergie (y compris pertes et écart statistique)","Électricité","TWh","Métropole","CVC","Branche énergie"],
  ["BE296","Consommation finale à usage énergétique d'électricité","Électricité","TWh","Métropole","CVC","Consommation finale énergétique"],
  ["BE297","Consommation finale d'électricité dans l'industrie","Électricité","TWh","Métropole","CVC","Industrie"],
  ["BE298","Consommation finale d'électricité dans le tertiaire","Électricité","TWh","Métropole","CVC","Tertiaire"],
  ["BE299","Consommation finale d'électricité dans le résidentiel","Électricité","TWh","Métropole","CVC","Résidentiel"],
  ["BE300","Consommation finale d'électricité, tous usages confondus","Électricité","TWh","Métropole","CVC","Consommation finale"],
  ["BE301","Consommation totale d'électricité (y compris écart statistique), déduction faite des pertes, de la consommation propre des centrales et de l'énergie absorbée par le pompage","Électricité","TWh","Métropole","CVC","Consommation totale"],
  ["BE302","Importations d'électricité de Belgique","Électricité","TWh","Métropole","Réelles","Importations"],
  ["BE303","Importations d'électricité d'Allemagne","Électricité","TWh","Métropole","Réelles","Importations"],
  ["BE304","Importations d'électricité de Suisse","Électricité","TWh","Métropole","Réelles","Importations"],
  ["BE305","Importations d'électricité d'Italie","Électricité","TWh","Métropole","Réelles","Importations"],
  ["BE306","Importations d'électricité d'Espagne","Électricité","TWh","Métropole","Réelles","Importations"],
  ["BE307","Importations d'électricité du Royaume-Uni","Électricité","TWh","Métropole","Réelles","Importations"],
  ["BE308","Exportations d'électricité vers la Belgique","Électricité","TWh","Métropole","Réelles","Exportations"],
  ["BE309","Exportations d'électricité vers l'Allemagne","Électricité","TWh","Métropole","Réelles","Exportations"],
  ["BE310","Exportations d'électricité vers la Suisse","Électricité","TWh","Métropole","Réelles","Exportations"],
  ["BE311","Exportations d'électricité vers l'Italie","Électricité","TWh","Métropole","Réelles","Exportations"],
  ["BE312","Exportations d'électricité vers l'Espagne","Électricité","TWh","Métropole","Réelles","Exportations"],
  ["BE313","Exportations d'électricité vers le Royaume-Uni","Électricité","TWh","Métropole","Réelles","Exportations"],
  ["BE314","Exportations d'électricité vers le Luxembourg","Électricité","TWh","Métropole","Réelles","Exportations"],
  ["BE315","Importations d'électricité","Électricité","Mtep","Métropole","Réelles","Importations"],
  ["BE316","Exportations d'électricité","Électricité","Mtep","Métropole","Réelles","Exportations"],
  ["BE317","Production brute d'électricité","Électricité","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE318","Production brute d'électricité nucléaire","Électricité","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE319","Production brute d'électricité hydraulique (y compris pompages)","Électricité","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE320","Production brute d'électricité géothermique","Électricité","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE321","Production brute d'électricité solaire photovoltaïque","Électricité","Mtep","Métropole","Réelles","Production primaire"],
  ["BE322","Production brute d'électricité issue des énergies marines","Électricité","Mtep","Métropole","Réelles","Production primaire"],
  ["BE323","Production brute d'électricité éolienne","Électricité","Mtep","Métropole","Réelles","Production primaire"],
  ["BE324","Production brute d'électricité des centrales thermiques classiques","Électricité","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE325","Production brute d'électricité, autres sources","Électricité","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE326","Production brute d'électricité hydraulique (hors pompages)","Électricité","Mtep","Métropole","Réelles","Production primaire"],
  ["BE327","Production brute d'électricité hydraulique des stations de pompages (STEP)","Électricité","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE328","Consommation propre des centrales électriques","Électricité","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE329","Production nette d'électricité","Électricité","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE330","Production nette d'électricité nucléaire","Électricité","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE331","Production nette d'électricité hydraulique (y compris pompages)","Électricité","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE332","Production nette d'électricité géothermique","Électricité","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE333","Production nette d'électricité solaire photovoltaïque","Électricité","Mtep","Métropole","Réelles","Production primaire"],
  ["BE334","Production nette d'électricité issue des énergies marines","Électricité","Mtep","Métropole","Réelles","Production primaire"],
  ["BE335","Production nette d'électricité éolienne","Électricité","Mtep","Métropole","Réelles","Production primaire"],
  ["BE336","Production nette d'électricité des centrales thermiques classiques","Électricité","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE337","Production nette d'électricité, autres sources","Électricité","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE338","Production nette d'électricité hydraulique (hors pompages)","Électricité","Mtep","Métropole","Réelles","Production primaire"],
  ["BE339","Production nette d'électricité hydraulique des stations de pompages (STEP)","Électricité","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE340","Énergie absorbée par le pompage","Électricité","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE341","Pertes de transport et de distribution d'électricité","Électricité","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE342","Usages internes de la branche énergie en électricité (hors pertes, consommation propre des centrales et énergie absorbée par le pompage)","Électricité","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE343","Consommation nette d'électricité de la branche énergie (y compris pertes et écart statistique)","Électricité","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE344","Consommation finale à usage énergétique d'électricité","Électricité","Mtep","Métropole","Réelles","Consommation finale énergétique"],
  ["BE345","Consommation finale d'électricité dans l'industrie","Électricité","Mtep","Métropole","Réelles","Industrie"],
  ["BE346","Consommation finale d'électricité dans le transport","Électricité","Mtep","Métropole","Réelles","Transport"],
  ["BE347","Consommation finale d'électricité dans le tertiaire","Électricité","Mtep","Métropole","Réelles","Tertiaire"],
  ["BE348","Consommation finale d'électricité dans le résidentiel","Électricité","Mtep","Métropole","Réelles","Résidentiel"],
  ["BE349","Consommation finale d'électricité dans l'agriculture","Électricité","Mtep","Métropole","Réelles","Agriculture"],
  ["BE350","Consommation finale d'électricité, tous usages confondus","Électricité","Mtep","Métropole","Réelles","Consommation finale"],
  ["BE351","Consommation totale d'électricité (y compris écart statistique), déduction faite des pertes, de la consommation propre des centrales et de l'énergie absorbée par le pompage","Électricité","Mtep","Métropole","Réelles","Consommation totale"],
  ["BE352","Pertes de transport et de distribution d'électricité","Électricité","Mtep","Métropole","CVC","Branche énergie"],
  ["BE353","Consommation nette d'électricité de la branche énergie (y compris pertes et écart statistique)","Électricité","Mtep","Métropole","CVC","Branche énergie"],
  ["BE354","Consommation finale à usage énergétique d'électricité","Électricité","Mtep","Métropole","CVC","Consommation finale énergétique"],
  ["BE355","Consommation finale d'électricité dans l'industrie","Électricité","Mtep","Métropole","CVC","Industrie"],
  ["BE356","Consommation finale d'électricité dans le tertiaire","Électricité","Mtep","Métropole","CVC","Tertiaire"],
  ["BE357","Consommation finale d'électricité dans le résidentiel","Électricité","Mtep","Métropole","CVC","Résidentiel"],
  ["BE358","Consommation finale d'électricité, tous usages confondus","Électricité","Mtep","Métropole","CVC","Consommation finale"],
  ["BE359","Consommation totale d'électricité (y compris écart statistique), déduction faite des pertes, de la consommation propre des centrales et de l'énergie absorbée par le pompage","Électricité","Mtep","Métropole","CVC","Consommation totale"],
  ["BE360","Production d'électricité et marges, en valeur","Électricité","M€ courants","Métropole","Réelles","Branche énergie"],
  ["BE361","Importations d'électricité, en valeur","Électricité","M€ courants","Métropole","Réelles","Importations"],
  ["BE362","Exportations d'électricité, en valeur","Électricité","M€ courants","Métropole","Réelles","Exportations"],
  ["BE363","Utilisation des réseaux de transport et de distribution d'électricité (hors pertes), en valeur","Électricité","M€ courants","Métropole","Réelles","Branche énergie"],
  ["BE364","Pertes de transport et de distribution d'électricité, en valeur","Électricité","M€ courants","Métropole","Réelles","Branche énergie"],
  ["BE365","Taxes sur l'électricité (toutes taxes, y compris TVA)","Électricité","M€ courants","Métropole","Réelles","Marges, Taxes, Subventions"],
  ["BE366","Subventions pour la production d'électricité (peréquation, obligations d'achat)","Électricité","M€ courants","Métropole","Réelles","Marges, Taxes, Subventions"],
  ["BE367","Dépense totale en électricité (TVA incluse pour résidentiel seulement)","Électricité","M€ courants","Métropole","Réelles","Consommation totale"],
  ["BE368","Dépense en électricité dans la branche énergie (hors branche électricité) (HTVA)","Électricité","M€ courants","Métropole","Réelles","Branche énergie"],
  ["BE369","Dépense en électricité dans l'industrie (HTVA)","Électricité","M€ courants","Métropole","Réelles","Industrie"],
  ["BE370","Dépense en électricité dans le transport (HTVA)","Électricité","M€ courants","Métropole","Réelles","Transport"],
  ["BE371","Dépense en électricité dans le tertiaire (HTVA)","Électricité","M€ courants","Métropole","Réelles","Tertiaire"],
  ["BE372","Dépense en électricité dans le résidentiel (TTC)","Électricité","M€ courants","Métropole","Réelles","Résidentiel"],
  ["BE373","Dépense en électricité dans l'agriculture (HTVA)","Électricité","M€ courants","Métropole","Réelles","Agriculture"],
  ["BE374","Dépense en électricité pour consommation finale (TVA incluse pour résidentiel seulement)","Électricité","M€ courants","Métropole","Réelles","Consommation finale"],
  ["BE375","Production nette d'électricité nucléaire vendue dans le cadre de l'Arenh, en valeur","Électricité","M€ courants","France continentale","Réelles","Branche énergie"],
  ["BE376","Production nette d'électricité sous obligation d'achat, en valeur","Électricité","M€ courants","France continentale","Réelles","Branche énergie"],
  ["BE377","Production nette d'électricité hydraulique sous obligation d'achat, en valeur","Électricité","M€ courants","France continentale","Réelles","Production primaire"],
  ["BE378","Production nette d'électricité éolienne sous obligation d'achat, en valeur","Électricité","M€ courants","France continentale","Réelles","Production primaire"],
  ["BE379","Production nette d'électricité solaire photovoltaïque sous obligation d'achat, en valeur","Électricité","M€ courants","France continentale","Réelles","Production primaire"],
  ["BE380","Production nette d'électricité des centrales thermiques classiques sous obligation d'achat, en valeur","Électricité","M€ courants","France continentale","Réelles","Branche énergie"],
  ["BE381","Subventions de peréquation pour la production d'électricité dans les zones non interconnectées","Électricité","M€ courants","Zones non interconnectées","Réelles","Marges, Taxes, Subventions"],
  ["BE382","Production brute hydraulique (hors pompages)","EnR et déchets","Mtep","Métropole","Réelles","Production primaire"],
  ["BE383","Production brute issue des énergies marines","EnR et déchets","Mtep","Métropole","Réelles","Production primaire"],
  ["BE384","Production brute éolienne","EnR et déchets","Mtep","Métropole","Réelles","Production primaire"],
  ["BE385","Production brute solaire photovoltaïque","EnR et déchets","Mtep","Métropole","Réelles","Production primaire"],
  ["BE386","Production brute d'énergies renouvelables électriques (hydraulique et énergies marines hors pompages, éolien, solaire photovoltaïque)","EnR et déchets","Mtep","Métropole","Réelles","Production primaire"],
  ["BE387","Production primaire - Géothermie","EnR et déchets","Mtep","Métropole","Réelles","Production primaire"],
  ["BE388","Production primaire - Solaire thermique","EnR et déchets","Mtep","Métropole","Réelles","Production primaire"],
  ["BE389","Production primaire - Pompes à chaleur","EnR et déchets","Mtep","Métropole","Réelles","Production primaire"],
  ["BE390","Production primaire - Déchets renouvelables","EnR et déchets","Mtep","Métropole","Réelles","Production primaire"],
  ["BE391","Production primaire - Biomasse solide (bois-énergie et résidus)","EnR et déchets","Mtep","Métropole","Réelles","Production primaire"],
  ["BE392","Production primaire - Bois-énergie","EnR et déchets","Mtep","Métropole","Réelles","Production primaire"],
  ["BE393","Production primaire - Résidus de l'agriculture et de l'industrie agro-alimentaire ","EnR et déchets","Mtep","Métropole","Réelles","Production primaire"],
  ["BE394","Production primaire - Biogaz","EnR et déchets","Mtep","Métropole","Réelles","Production primaire"],
  ["BE395","Production primaire - Biocarburants (biodiesel et bioessence)","EnR et déchets","Mtep","Métropole","Réelles","Production primaire"],
  ["BE396","Production primaire - Biodiesel","EnR et déchets","Mtep","Métropole","Réelles","Production primaire"],
  ["BE397","Production primaire - Bioessence","EnR et déchets","Mtep","Métropole","Réelles","Production primaire"],
  ["BE398","Production primaire d'énergies renouvelables thermiques (géothermie, solaire thermique, pompes à chaleur, déchets renouvelables, biomasse solide, biogaz, biocarburants)","EnR et déchets","Mtep","Métropole","Réelles","Production primaire"],
  ["BE399","Production primaire d'énergies renouvelables","EnR et déchets","Mtep","Métropole","Réelles","Production primaire"],
  ["BE400","Production primaire - Déchets non renouvelables","EnR et déchets","Mtep","Métropole","Réelles","Production primaire"],
  ["BE401","Production primaire d'énergies renouvelables thermiques et déchets","EnR et déchets","Mtep","Métropole","Réelles","Production primaire"],
  ["BE402","Production primaire d'énergies renouvelables et déchets","EnR et déchets","Mtep","Métropole","Réelles","Production primaire"],
  ["BE403","Importations de biocarburants (biodiesel et bioessence)","EnR et déchets","Mtep","Métropole","Réelles","Importations"],
  ["BE404","Importations de biodiesel","EnR et déchets","Mtep","Métropole","Réelles","Importations"],
  ["BE405","Importations de bioessence","EnR et déchets","Mtep","Métropole","Réelles","Importations"],
  ["BE406","Exportations de biocarburants (biodiesel et bioessence)","EnR et déchets","Mtep","Métropole","Réelles","Exportations"],
  ["BE407","Exportations de biodiesel","EnR et déchets","Mtep","Métropole","Réelles","Exportations"],
  ["BE408","Exportations de bioessence","EnR et déchets","Mtep","Métropole","Réelles","Exportations"],
  ["BE409","Consommation primaire de biocarburants (biodiesel et bioessence)","EnR et déchets","Mtep","Métropole","Réelles","Consommation primaire"],
  ["BE410","Consommation primaire de biodiesel","EnR et déchets","Mtep","Métropole","Réelles","Consommation primaire"],
  ["BE411","Consommation primaire de bioessence","EnR et déchets","Mtep","Métropole","Réelles","Consommation primaire"],
  ["BE412","Consommation primaire d'énergies renouvelables électriques (hydraulique et énergies marines hors pompages, éolien, solaire photovoltaïque)","EnR et déchets","Mtep","Métropole","Réelles","Consommation primaire"],
  ["BE413","Consommation primaire d'énergies renouvelables thermiques (géothermie, solaire thermique, pompes à chaleur, déchets renouvelables, biomasse solide, biogaz, biocarburants)","EnR et déchets","Mtep","Métropole","Réelles","Consommation primaire"],
  ["BE414","Consommation primaire d'énergies renouvelables","EnR et déchets","Mtep","Métropole","Réelles","Consommation primaire"],
  ["BE415","Consommation primaire d'énergies renouvelables thermiques et déchets","EnR et déchets","Mtep","Métropole","Réelles","Consommation primaire"],
  ["BE416","Consommation primaire d'énergies renouvelables et déchets","EnR et déchets","Mtep","Métropole","Réelles","Consommation primaire"],
  ["BE417","Consommation nette d'énergies renouvelables thermiques et déchets dans la branche énergie (y compris écart statistique)","EnR et déchets","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE418","Consommation d'énergies renouvelables thermiques et déchets pour la production d'électricité seule","EnR et déchets","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE419","Consommation d'énergies renouvelables thermiques et déchets pour la cogénération","EnR et déchets","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE420","Consommation d'énergies renouvelables thermiques et déchets pour la production de chaleur seule","EnR et déchets","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE421","Injections de biométhane dans les réseaux de gaz naturel","EnR et déchets","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE422","Usages internes de la branche énergie en énergies renouvelables thermiques et déchets","EnR et déchets","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE423","Consommation finale à usage énergétique d'énergies renouvelables thermiques et déchets","EnR et déchets","Mtep","Métropole","Réelles","Consommation finale énergétique"],
  ["BE424","Consommation finale d'énergies renouvelables thermiques et déchets dans l'industrie","EnR et déchets","Mtep","Métropole","Réelles","Industrie"],
  ["BE425","Consommation finale d'énergies renouvelables thermiques et déchets dans le transport","EnR et déchets","Mtep","Métropole","Réelles","Transport"],
  ["BE426","Consommation finale d'énergies renouvelables thermiques et déchets dans le tertiaire","EnR et déchets","Mtep","Métropole","Réelles","Tertiaire"],
  ["BE427","Consommation finale d'énergies renouvelables thermiques et déchets dans le résidentiel","EnR et déchets","Mtep","Métropole","Réelles","Résidentiel"],
  ["BE428","Consommation finale d'énergies renouvelables thermiques et déchets dans l'agriculture","EnR et déchets","Mtep","Métropole","Réelles","Agriculture"],
  ["BE429","Consommation finale d'énergies renouvelables thermiques et déchets, tous usages confondus","EnR et déchets","Mtep","Métropole","Réelles","Consommation finale"],
  ["BE430","Consommation primaire d'énergies renouvelables électriques (hydraulique et énergies marines hors pompages, éolien, solaire photovoltaïque)","EnR et déchets","Mtep","Métropole","CVC","Consommation primaire"],
  ["BE431","Consommation primaire d'énergies renouvelables thermiques (géothermie, solaire thermique, pompes à chaleur, déchets renouvelables, biomasse solide, biogaz, biocarburants)","EnR et déchets","Mtep","Métropole","CVC","Consommation primaire"],
  ["BE432","Consommation primaire d'énergies renouvelables","EnR et déchets","Mtep","Métropole","CVC","Consommation primaire"],
  ["BE433","Consommation primaire d'énergies renouvelables thermiques et déchets","EnR et déchets","Mtep","Métropole","CVC","Consommation primaire"],
  ["BE434","Consommation primaire d'énergies renouvelables et déchets","EnR et déchets","Mtep","Métropole","CVC","Consommation primaire"],
  ["BE435","Consommation nette d'énergies renouvelables thermiques et déchets dans la branche énergie (y compris écart statistique)","EnR et déchets","Mtep","Métropole","CVC","Branche énergie"],
  ["BE436","Consommation d'énergies renouvelables thermiques et déchets pour la production de chaleur seule","EnR et déchets","Mtep","Métropole","CVC","Branche énergie"],
  ["BE437","Consommation finale à usage énergétique d'énergies renouvelables thermiques et déchets","EnR et déchets","Mtep","Métropole","CVC","Consommation finale énergétique"],
  ["BE438","Consommation finale d'énergies renouvelables thermiques et déchets dans le tertiaire","EnR et déchets","Mtep","Métropole","CVC","Tertiaire"],
  ["BE439","Consommation finale d'énergies renouvelables thermiques et déchets dans le résidentiel","EnR et déchets","Mtep","Métropole","CVC","Résidentiel"],
  ["BE440","Consommation finale d'énergies renouvelables thermiques et déchets, tous usages confondus","EnR et déchets","Mtep","Métropole","CVC","Consommation finale"],
  ["BE441","Injections de biométhane dans les réseaux de gaz naturel, en valeur","EnR et déchets","M€ courants","Métropole","Réelles","Branche énergie"],
  ["BE442","Production totale de chaleur (vendue)","Chaleur vendue","TWh","Métropole","Réelles","Branche énergie"],
  ["BE443","Production de chaleur (vendue) des centrales de cogénération","Chaleur vendue","TWh","Métropole","Réelles","Branche énergie"],
  ["BE444","Production de chaleur (vendue) des centrales calogènes","Chaleur vendue","TWh","Métropole","Réelles","Branche énergie"],
  ["BE445","Pertes de transport et de distribution de chaleur (vendue)","Chaleur vendue","TWh","Métropole","Réelles","Branche énergie"],
  ["BE446","Usages internes de la branche énergie en chaleur (vendue)","Chaleur vendue","TWh","Métropole","Réelles","Branche énergie"],
  ["BE447","Consommation nette de chaleur (vendue) de la branche énergie (y compris pertes et écart statistique)","Chaleur vendue","TWh","Métropole","Réelles","Branche énergie"],
  ["BE448","Consommation finale à usage énergétique de chaleur (vendue)","Chaleur vendue","TWh","Métropole","Réelles","Consommation finale énergétique"],
  ["BE449","Consommation finale de chaleur (vendue) dans l'industrie","Chaleur vendue","TWh","Métropole","Réelles","Industrie"],
  ["BE450","Consommation finale de chaleur (vendue) dans le transport","Chaleur vendue","TWh","Métropole","Réelles","Transport"],
  ["BE451","Consommation finale de chaleur (vendue) dans le tertiaire","Chaleur vendue","TWh","Métropole","Réelles","Tertiaire"],
  ["BE452","Consommation finale de chaleur (vendue) dans le résidentiel","Chaleur vendue","TWh","Métropole","Réelles","Résidentiel"],
  ["BE453","Consommation finale de chaleur (vendue) dans l'agriculture","Chaleur vendue","TWh","Métropole","Réelles","Agriculture"],
  ["BE454","Consommation finale de chaleur (vendue), tous usages confondus","Chaleur vendue","TWh","Métropole","Réelles","Consommation finale"],
  ["BE455","Consommation totale de chaleur (vendue), hors pertes et écart statistique","Chaleur vendue","TWh","Métropole","Réelles","Consommation totale"],
  ["BE456","Pertes de transport et de distribution de chaleur (vendue)","Chaleur vendue","TWh","Métropole","CVC","Branche énergie"],
  ["BE457","Consommation nette de chaleur (vendue) de la branche énergie (y compris pertes et écart statistique)","Chaleur vendue","TWh","Métropole","CVC","Branche énergie"],
  ["BE458","Consommation finale à usage énergétique de chaleur (vendue)","Chaleur vendue","TWh","Métropole","CVC","Consommation finale énergétique"],
  ["BE459","Consommation finale de chaleur (vendue) dans le tertiaire","Chaleur vendue","TWh","Métropole","CVC","Tertiaire"],
  ["BE460","Consommation finale de chaleur (vendue) dans le résidentiel","Chaleur vendue","TWh","Métropole","CVC","Résidentiel"],
  ["BE461","Consommation finale de chaleur (vendue), tous usages confondus","Chaleur vendue","TWh","Métropole","CVC","Consommation finale"],
  ["BE462","Consommation totale de chaleur (vendue), hors pertes et écart statistique","Chaleur vendue","TWh","Métropole","CVC","Consommation totale"],
  ["BE463","Production totale de chaleur (vendue)","Chaleur vendue","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE464","Production de chaleur (vendue) des centrales de cogénération","Chaleur vendue","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE465","Production de chaleur (vendue) des centrales calogènes","Chaleur vendue","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE466","Pertes de transport et de distribution de chaleur (vendue)","Chaleur vendue","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE467","Usages internes de la branche énergie en chaleur (vendue)","Chaleur vendue","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE468","Consommation nette de chaleur (vendue) de la branche énergie (y compris pertes et écart statistique)","Chaleur vendue","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE469","Consommation finale à usage énergétique de chaleur (vendue)","Chaleur vendue","Mtep","Métropole","Réelles","Consommation finale énergétique"],
  ["BE470","Consommation finale de chaleur (vendue) dans l'industrie","Chaleur vendue","Mtep","Métropole","Réelles","Industrie"],
  ["BE471","Consommation finale de chaleur (vendue) dans le transport","Chaleur vendue","Mtep","Métropole","Réelles","Transport"],
  ["BE472","Consommation finale de chaleur (vendue) dans le tertiaire","Chaleur vendue","Mtep","Métropole","Réelles","Tertiaire"],
  ["BE473","Consommation finale de chaleur (vendue) dans le résidentiel","Chaleur vendue","Mtep","Métropole","Réelles","Résidentiel"],
  ["BE474","Consommation finale de chaleur (vendue) dans l'agriculture","Chaleur vendue","Mtep","Métropole","Réelles","Agriculture"],
  ["BE475","Consommation finale de chaleur (vendue), tous usages confondus","Chaleur vendue","Mtep","Métropole","Réelles","Consommation finale"],
  ["BE476","Consommation totale de chaleur (vendue), hors pertes et écart statistique","Chaleur vendue","Mtep","Métropole","Réelles","Consommation totale"],
  ["BE477","Pertes de transport et de distribution de chaleur (vendue)","Chaleur vendue","Mtep","Métropole","CVC","Branche énergie"],
  ["BE478","Consommation nette de chaleur (vendue) de la branche énergie (y compris pertes et écart statistique)","Chaleur vendue","Mtep","Métropole","CVC","Branche énergie"],
  ["BE479","Consommation finale à usage énergétique de chaleur (vendue)","Chaleur vendue","Mtep","Métropole","CVC","Consommation finale énergétique"],
  ["BE480","Consommation finale de chaleur (vendue) dans le tertiaire","Chaleur vendue","Mtep","Métropole","CVC","Tertiaire"],
  ["BE481","Consommation finale de chaleur (vendue) dans le résidentiel","Chaleur vendue","Mtep","Métropole","CVC","Résidentiel"],
  ["BE482","Consommation finale de chaleur (vendue), tous usages confondus","Chaleur vendue","Mtep","Métropole","CVC","Consommation finale"],
  ["BE483","Consommation totale de chaleur (vendue), hors pertes et écart statistique","Chaleur vendue","Mtep","Métropole","CVC","Consommation totale"],
  ["BE484","Production d'énergie primaire, toutes énergies confondues","Toutes énergies","Mtep","Métropole","Réelles","Production primaire"],
  ["BE485","Importations d'énergie, toutes énergies confondues","Toutes énergies","Mtep","Métropole","Réelles","Importations"],
  ["BE486","Exportations d'énergie, toutes énergies confondues","Toutes énergies","Mtep","Métropole","Réelles","Exportations"],
  ["BE487","Variations de stocks de produits énergétiques (stocks au 1er janvier N - stocks au 31 décembre N), toutes énergies confondues","Toutes énergies","Mtep","Métropole","Réelles","Stocks"],
  ["BE488","Soutes internationales (aériennes et maritimes), toutes énergies confondues","Toutes énergies","Mtep","Métropole","Réelles","Soutes"],
  ["BE489","Consommation primaire d'énergie, toutes énergies confondues","Toutes énergies","Mtep","Métropole","Réelles","Consommation primaire"],
  ["BE490","Consommation nette de la branche énergie (y compris pertes et écart statistique), toutes énergies confondues","Toutes énergies","Mtep","Métropole","Réelles","Branche énergie"],
  ["BE491","Consommation finale à usage énergétique, toutes énergies confondues","Toutes énergies","Mtep","Métropole","Réelles","Consommation finale énergétique"],
  ["BE492","Consommation finale dans l'industrie, toutes énergies confondues","Toutes énergies","Mtep","Métropole","Réelles","Industrie"],
  ["BE493","Consommation finale dans le transport, toutes énergies confondues","Toutes énergies","Mtep","Métropole","Réelles","Transport"],
  ["BE494","Consommation finale dans le tertiaire, toutes énergies confondues","Toutes énergies","Mtep","Métropole","Réelles","Tertiaire"],
  ["BE495","Consommation finale dans le résidentiel, toutes énergies confondues","Toutes énergies","Mtep","Métropole","Réelles","Résidentiel"],
  ["BE496","Consommation finale dans le résidentiel-tertiaire, toutes énergies confondues","Toutes énergies","Mtep","Métropole","Réelles","Résidentiel-tertiaire"],
  ["BE497","Consommation finale dans l'agriculture, toutes énergies confondues","Toutes énergies","Mtep","Métropole","Réelles","Agriculture"],
  ["BE498","Consommation finale non affectée à un secteur, toutes énergies confondues (correspond à la consommation finale de chaleur vendue entre 2000 et 2006)","Toutes énergies","Mtep","Métropole","Réelles","Consommation finale"],
  ["BE499","Consommation finale à usage non énergétique, toutes énergies confondues","Toutes énergies","Mtep","Métropole","Réelles","Usages non énergétiques"],
  ["BE500","Consommation finale, tous usages confondus, toutes énergies confondues","Toutes énergies","Mtep","Métropole","Réelles","Consommation finale"],
  ["BE501","Consommation primaire d'énergie, toutes énergies confondues","Toutes énergies","Mtep","Métropole","CVC","Consommation primaire"],
  ["BE502","Consommation nette de la branche énergie (y compris pertes et écart statistique), toutes énergies confondues","Toutes énergies","Mtep","Métropole","CVC","Branche énergie"],
  ["BE503","Consommation finale à usage énergétique, toutes énergies confondues","Toutes énergies","Mtep","Métropole","CVC","Consommation finale énergétique"],
  ["BE504","Consommation finale dans l'industrie, toutes énergies confondues","Toutes énergies","Mtep","Métropole","CVC","Industrie"],
  ["BE505","Consommation finale dans le tertiaire, toutes énergies confondues","Toutes énergies","Mtep","Métropole","CVC","Tertiaire"],
  ["BE506","Consommation finale dans le résidentiel, toutes énergies confondues","Toutes énergies","Mtep","Métropole","CVC","Résidentiel"],
  ["BE507","Consommation finale dans le résidentiel-tertiaire, toutes énergies confondues","Toutes énergies","Mtep","Métropole","CVC","Résidentiel-tertiaire"],
  ["BE508","Consommation finale non affectée à un secteur, toutes énergies confondues (correspond à la consommation finale de chaleur vendue entre 2000 et 2006)","Toutes énergies","Mtep","Métropole","CVC","Consommation finale"],
  ["BE509","Consommation finale, tous usages confondus, toutes énergies confondues","Toutes énergies","Mtep","Métropole","CVC","Consommation finale"],
  ["BE510","Taux d'indépendance énergétique","Toutes énergies","%","Métropole","Réelles","Divers"],
  ["BE511","Taux d'indépendance énergétique","Toutes énergies","%","Métropole","CVC","Divers"],
  ["BE512","Émissions de CO2 liées à la combustion d'énergie dans la branche énergie (toutes énergies confondues)","Toutes énergies","Mt CO2","Métropole","CVC","Émissions de CO2"],
  ["BE513","Émissions de CO2 liées à la combustion d'énergie pour la production d'électricité (tous combustibles confondus)","Toutes énergies","Mt CO2","Métropole","CVC","Émissions de CO2"],
  ["BE514","Émissions de CO2 liées à la combustion d'énergie dans l'industrie (toutes énergies confondues)","Toutes énergies","Mt CO2","Métropole","CVC","Émissions de CO2"],
  ["BE515","Émissions de CO2 liées à la combustion d'énergie dans le résidentiel-tertiaire (toutes énergies confondues)","Toutes énergies","Mt CO2","Métropole","CVC","Émissions de CO2"],
  ["BE516","Émissions de CO2 liées à la combustion d'énergie dans l'agriculture (toutes énergies confondues)","Toutes énergies","Mt CO2","Métropole","CVC","Émissions de CO2"],
  ["BE517","Émissions de CO2 liées à la combustion d'énergie dans le transport (hors soutes internationales, toutes énergies confondues)","Toutes énergies","Mt CO2","Métropole","CVC","Émissions de CO2"],
  ["BE518","Émissions de CO2 liées à la combustion de produits pétroliers (hors soutes internationales, tous secteurs confondus)","Pétrole","Mt CO2","Métropole","CVC","Émissions de CO2"],
  ["BE519","Émissions de CO2 liées à la combustion de gaz naturel (tous secteurs confondus)","Gaz naturel","Mt CO2","Métropole","CVC","Émissions de CO2"],
  ["BE520","Émissions de CO2 liées à la combustion de charbon (tous secteurs confondus)","Charbon","Mt CO2","Métropole","CVC","Émissions de CO2"],
  ["BE521","Émissions de CO2 liées à la combustion de déchets non renouvelables (tous secteurs confondus)","EnR et déchets","Mt CO2","Métropole","CVC","Émissions de CO2"],
  ["BE522","Émissions de CO2 liées à la combustion d'énergie (hors soutes internationales, toutes énergies confondues, tous secteurs confondus)","Toutes énergies","Mt CO2","Métropole","CVC","Émissions de CO2"],
  ["BE523","Émissions de CO2 liées à la combustion d'énergie dans la branche énergie (toutes énergies confondues)","Toutes énergies","Mt CO2","Métropole","Réelles","Émissions de CO2"],
  ["BE524","Émissions de CO2 liées à la combustion d'énergie pour la production d'électricité (tous combustibles confondus)","Toutes énergies","Mt CO2","Métropole","Réelles","Émissions de CO2"],
  ["BE525","Émissions de CO2 liées à la combustion d'énergie dans l'industrie (toutes énergies confondues)","Toutes énergies","Mt CO2","Métropole","Réelles","Émissions de CO2"],
  ["BE526","Émissions de CO2 liées à la combustion d'énergie dans le résidentiel-tertiaire (toutes énergies confondues)","Toutes énergies","Mt CO2","Métropole","Réelles","Émissions de CO2"],
  ["BE527","Émissions de CO2 liées à la combustion d'énergie dans l'agriculture (toutes énergies confondues)","Toutes énergies","Mt CO2","Métropole","Réelles","Émissions de CO2"],
  ["BE528","Émissions de CO2 liées à la combustion d'énergie dans le transport (hors soutes internationales, toutes énergies confondues)","Toutes énergies","Mt CO2","Métropole","Réelles","Émissions de CO2"],
  ["BE529","Émissions de CO2 liées à la combustion d'énergie (hors soutes internationales, toutes énergies confondues, tous secteurs confondus)","Toutes énergies","Mt CO2","Métropole","Réelles","Émissions de CO2"],
  ["BE530","Importations de pétrole brut dans les DOM","Pétrole","Mtep","DOM","Réelles","Importations"],
  ["BE531","Variations de stocks de pétrole brut dans les DOM (stocks au 1er janvier N - stocks au 31 décembre N)","Pétrole","Mtep","DOM","Réelles","Stocks"],
  ["BE532","Disponibilités (Consommation primaire) en pétrole brut dans les DOM","Pétrole","Mtep","DOM","Réelles","Consommation primaire"],
  ["BE533","Importations de produits raffinés dans les DOM","Pétrole","Mtep","DOM","Réelles","Importations"],
  ["BE534","Exportations de produits raffinés dans les DOM","Pétrole","Mtep","DOM","Réelles","Exportations"],
  ["BE535","Variations de stocks de produits raffinés  dans les DOM (stocks au 1er janvier N - stocks au 31 décembre N)","Pétrole","Mtep","DOM","Réelles","Stocks"],
  ["BE536","Soutes maritimes internationales - ports des DOM (produits raffinés)","Pétrole","Mtep","DOM","Réelles","Soutes"],
  ["BE537","Soutes aériennes internationales - aéroports des DOM (produits raffinés)","Pétrole","Mtep","DOM","Réelles","Soutes"],
  ["BE538","Consommation primaire de pétrole dans les DOM (Total brut et raffinés)","Pétrole","Mtep","DOM","Réelles","Consommation primaire"],
  ["BE539","Consommation de pétrole brut des raffineries dans les DOM","Pétrole","Mtep","DOM","Réelles","Branche énergie"],
  ["BE540","Consommation de produits raffinés pour la production d'électricité et de chaleur dans les DOM","Pétrole","Mtep","DOM","Réelles","Branche énergie"],
  ["BE541","Production brute des raffineries en produits raffinés dans les DOM","Pétrole","Mtep","DOM","Réelles","Branche énergie"],
  ["BE542","Consommation finale à usage énergétique de produits raffinés dans les DOM","Pétrole","Mtep","DOM","Réelles","Consommation finale énergétique"],
  ["BE543","Consommation finale de produits raffinés dans l'industrie, dans les DOM","Pétrole","Mtep","DOM","Réelles","Industrie"],
  ["BE544","Consommation finale de produits raffinés dans le transport, dans les DOM (hors biocarburants, trafic aérien vers la métropole inclus)","Pétrole","Mtep","DOM","Réelles","Transport"],
  ["BE545","Consommation finale de produits raffinés dans le résidentiel-tertiaire, dans les DOM","Pétrole","Mtep","DOM","Réelles","Résidentiel-tertiaire"],
  ["BE546","Consommation finale de produits raffinés dans l'agriculture, dans les DOM","Pétrole","Mtep","DOM","Réelles","Agriculture"],
  ["BE547","Consommation finale à usage non énergétique de produits raffinés dans les DOM","Pétrole","Mtep","DOM","Réelles","Usages non énergétiques"],
  ["BE548","Consommation finale de produits raffinés, tous usages confondus, dans les DOM","Pétrole","Mtep","DOM","Réelles","Consommation finale"],
  ["BE549","Consommation nette de pétrole (brut et raffinés) de la branche énergie dans les DOM (y compris écart statistique et transferts)","Pétrole","Mtep","DOM","Réelles","Branche énergie"],
  ["BE550","Consommation totale brute de produits raffinés dans les DOM (hors écart statistique)","Pétrole","Mtep","DOM","Réelles","Consommation totale"],
  ["BE551","Importations de charbon dans les DOM","Charbon","Mtep","DOM","Réelles","Importations"],
  ["BE552","Variations de stocks de charbon dans les DOM (stocks au 1er janvier N - stocks au 31 décembre N)","Charbon","Mtep","DOM","Réelles","Stocks"],
  ["BE553","Consommation primaire de charbon dans les DOM (tous produits confondus)","Charbon","Mtep","DOM","Réelles","Consommation primaire"],
  ["BE554","Consommation de charbon pour la production d'électricité et de chaleur dans les DOM","Charbon","Mtep","DOM","Réelles","Branche énergie"],
  ["BE555","Production brute d'électricité dans les DOM","Électricité","Mtep","DOM","Réelles","Branche énergie"],
  ["BE556","Pertes et usages internes de la branche énergie en électricité dans les DOM (y compris consommation propre des centrales et énergie absorbée par le pompage)","Électricité","Mtep","DOM","Réelles","Branche énergie"],
  ["BE557","Consommation nette d'électricité de la branche énergie dans les DOM (y compris pertes et écart statistique)","Électricité","Mtep","DOM","Réelles","Branche énergie"],
  ["BE558","Consommation finale à usage énergétique d'électricité dans les DOM","Électricité","Mtep","DOM","Réelles","Consommation finale énergétique"],
  ["BE559","Consommation finale d'électricité dans l'industrie, le transport et l'agriculture, dans les DOM","Électricité","Mtep","DOM","Réelles","Consommation finale énergétique"],
  ["BE560","Consommation finale d'électricité dans le tertiaire, dans les DOM","Électricité","Mtep","DOM","Réelles","Tertiaire"],
  ["BE561","Consommation finale d'électricité dans le résidentiel, dans les DOM","Électricité","Mtep","DOM","Réelles","Résidentiel"],
  ["BE562","Consommation finale d'électricité, tous usages confondus, dans les DOM","Électricité","Mtep","DOM","Réelles","Consommation finale"],
  ["BE563","Production brute d'énergies renouvelables électriques dans les DOM (hydraulique et énergies marines hors pompages, éolien, solaire photovoltaïque)","EnR et déchets","Mtep","DOM","Réelles","Production primaire"],
  ["BE564","Production primaire d'énergies renouvelables thermiques et déchets dans les DOM","EnR et déchets","Mtep","DOM","Réelles","Production primaire"],
  ["BE565","Production primaire d'énergies renouvelables et déchets dans les DOM","EnR et déchets","Mtep","DOM","Réelles","Production primaire"],
  ["BE566","Consommation primaire d'énergies renouvelables électriques dans les DOM (hydraulique et énergies marines hors pompages, éolien, solaire photovoltaïque)","EnR et déchets","Mtep","DOM","Réelles","Consommation primaire"],
  ["BE567","Consommation primaire d'énergies renouvelables thermiques et déchets dans les DOM","EnR et déchets","Mtep","DOM","Réelles","Consommation primaire"],
  ["BE568","Consommation primaire d'énergies renouvelables et déchets dans les DOM","EnR et déchets","Mtep","DOM","Réelles","Consommation primaire"],
  ["BE569","Consommation nette d'énergies renouvelables thermiques et déchets dans la branche énergie, dans les DOM (y compris écart statistique)","EnR et déchets","Mtep","DOM","Réelles","Branche énergie"],
  ["BE570","Consommation d'énergies renouvelables thermiques et déchets pour la production d'électricité et de chaleur dans les DOM","EnR et déchets","Mtep","DOM","Réelles","Branche énergie"],
  ["BE571","Consommation finale à usage énergétique d'énergies renouvelables thermiques et déchets dans les DOM","EnR et déchets","Mtep","DOM","Réelles","Consommation finale énergétique"],
  ["BE572","Consommation finale d'énergies renouvelables thermiques et déchets dans le tertiaire, dans les DOM","EnR et déchets","Mtep","DOM","Réelles","Tertiaire"],
  ["BE573","Consommation finale d'énergies renouvelables thermiques et déchets dans le résidentiel, dans les DOM","EnR et déchets","Mtep","DOM","Réelles","Résidentiel"],
  ["BE574","Consommation finale d'énergies renouvelables thermiques et déchets, tous usages confondus, dans les DOM","EnR et déchets","Mtep","DOM","Réelles","Consommation finale"],
  ["BE575","Production d'énergie primaire dans les DOM, toutes énergies confondues","Toutes énergies","Mtep","DOM","Réelles","Production primaire"],
  ["BE576","Importations d'énergie dans les DOM, toutes énergies confondues","Toutes énergies","Mtep","DOM","Réelles","Importations"],
  ["BE577","Exportations d'énergie dans les DOM, toutes énergies confondues","Toutes énergies","Mtep","DOM","Réelles","Exportations"],
  ["BE578","Variations de stocks de produits énergétiques dans les DOM (stocks au 1er janvier N - stocks au 31 décembre N), toutes énergies confondues","Toutes énergies","Mtep","DOM","Réelles","Stocks"],
  ["BE579","Soutes internationales (aériennes et maritimes), toutes énergies confondues - ports et aéroports des DOM","Toutes énergies","Mtep","DOM","Réelles","Soutes"],
  ["BE580","Consommation primaire d'énergie dans les DOM, toutes énergies confondues","Toutes énergies","Mtep","DOM","Réelles","Consommation primaire"],
  ["BE581","Consommation nette de la branche énergie dans les DOM (y compris pertes et écart statistique), toutes énergies confondues","Toutes énergies","Mtep","DOM","Réelles","Branche énergie"],
  ["BE582","Consommation finale à usage énergétique dans les DOM, toutes énergies confondues","Toutes énergies","Mtep","DOM","Réelles","Consommation finale énergétique"],
  ["BE583","Consommation finale dans l'industrie, le transport et l'agriculture, dans les DOM, toutes énergies confondues (trafic aérien vers la métropole inclus)","Toutes énergies","Mtep","DOM","Réelles","Consommation finale énergétique"],
  ["BE584","Consommation finale dans le résidentiel-tertiaire, dans les DOM, toutes énergies confondues","Toutes énergies","Mtep","DOM","Réelles","Résidentiel-tertiaire"],
  ["BE585","Consommation finale à usage non énergétique dans les DOM, toutes énergies confondues","Toutes énergies","Mtep","DOM","Réelles","Usages non énergétiques"],
  ["BE586","Consommation finale dans les DOM, tous usages confondus, toutes énergies confondues","Toutes énergies","Mtep","DOM","Réelles","Consommation finale"],
  ["BE587","Taux d'indépendance énergétique des DOM","Toutes énergies","%","DOM","Réelles","Divers"],
  ["BE588","Dépense moyenne par ménage en énergies domestiques (électricité, gaz, combustibles liquides, combustibles solides, eau chaude et vapeur d'eau)","Toutes énergies","€ courants","France","Réelles","Dépenses des ménages"],
  ["BE589","Dépense moyenne par ménage en électricité (dans le logement)","Toutes énergies","€ courants","France","Réelles","Dépenses des ménages"],
  ["BE590","Dépense moyenne par ménage en gaz (dans le logement)","Toutes énergies","€ courants","France","Réelles","Dépenses des ménages"],
  ["BE591","Dépense moyenne par ménage en combustibles liquides (dans le logement)","Toutes énergies","€ courants","France","Réelles","Dépenses des ménages"],
  ["BE592","Dépense moyenne par ménage en combustibles solides (dans le logement)","Toutes énergies","€ courants","France","Réelles","Dépenses des ménages"],
  ["BE593","Dépense moyenne par ménage en eau chaude et vapeur d'eau (dans le logement)","Toutes énergies","€ courants","France","Réelles","Dépenses des ménages"],
  ["BE594","Dépense moyenne par ménage en carburants et lubrifiants","Toutes énergies","€ courants","France","Réelles","Dépenses des ménages"],
  ["BE595","Dépense moyenne par ménage en énergie (toutes énergies confondues : énergies domestiques, carburants et lubrifiants)","Toutes énergies","€ courants","France","Réelles","Dépenses des ménages"],
  ["BE596","Dépenses totales des ménages en énergie (toutes énergies confondues : énergies domestiques, carburants et lubrifiants)","Toutes énergies","M€ courants","France","Réelles","Dépenses des ménages"],
  ["BE597","Part de l'énergie dans le budget des ménages (hors loyers imputés et services d'intermédiation financière indirectement mesurés)","Toutes énergies","%","France","Réelles","Dépenses des ménages"],
  ["BE598","Part de l'énergie dans la consommation effective des ménages","Toutes énergies","%","France","Réelles","Dépenses des ménages"],
  ["BE599","Facture énergétique de la France, en millions d'euros 2017","Toutes énergies","M€2017","France","Réelles","Facture énergétique"],
  ["BE600","Facture charbonnière de la France, en millions d'euros 2017","Charbon","M€2017","France","Réelles","Facture énergétique"],
  ["BE601","Facture en pétrole brut de la France, en millions d'euros 2017","Pétrole","M€2017","France","Réelles","Facture énergétique"],
  ["BE602","Facture en produits raffinés de la France, en millions d'euros 2017","Pétrole","M€2017","France","Réelles","Facture énergétique"],
  ["BE603","Facture gazière de la France, en millions d'euros 2017","Gaz naturel","M€2017","France","Réelles","Facture énergétique"],
  ["BE604","Facture électrique de la France, en millions d'euros 2017","Électricité","M€2017","France","Réelles","Facture énergétique"],
  ["BE605","Facture en biocarburants de la France, en millions d'euros 2017","EnR et déchets","M€2017","France","Réelles","Facture énergétique"],
  ["BE606","Taux de change moyen US Dollar / Euro","-","-","-","Réelles","Cours-Prix"],
  ["BE607","Taux de change moyen Euro / US Dollar","-","-","-","Réelles","Cours-Prix"],
  ["BE608","Prix spot du charbon-vapeur sur le marché Anvers-Rotterdam-Amsterdam (North West European steam coal marker)","Charbon","$ / tonne","-","Réelles","Cours-Prix"],
  ["BE609","Prix spot du charbon-vapeur sur le marché Anvers-Rotterdam-Amsterdam (North West European steam coal marker)","Charbon","€ / tonne","-","Réelles","Cours-Prix"],
  ["BE610","Cours du baril de Brent (Baril de référence, pétrole de mer du Nord)","Pétrole","$ / baril","-","Réelles","Cours-Prix"],
  ["BE611","Cours du baril de Brent (Baril de référence, pétrole de mer du Nord)","Pétrole","€ / baril","-","Réelles","Cours-Prix"],
  ["BE612","Prix spot du gaz NBP (National Balancing Point) à Londres","Gaz naturel","$ / Mbtu","-","Réelles","Cours-Prix"],
  ["BE613","Prix spot du gaz NBP (National Balancing Point) à Londres","Gaz naturel","€ / MWh","-","Réelles","Cours-Prix"],
  ["BE614","Prix baseload mensuel moyen de l'électricité Epex spot France","Électricité","€ / MWh","-","Réelles","Cours-Prix"],
  ["BE615","Prix peakload mensuel moyen de l'électricité Epex spot France","Électricité","€ / MWh","-","Réelles","Cours-Prix"],
  ["BE616","Nombre de degrés-jours unifiés sur la période de chauffe (janvier à mai, octobre à décembre)","-","-","Métropole","Réelles","Divers"]
]