module.exports = [
  ["OE","Dépenses des occupants","OEO1","Loyers (ou redevances) payé par les occupants","OEO1","Loyers (ou redevances) payé par les occupants","OEO111","Loyers réels"],
  ["OE","Dépenses des occupants","OEO1","Loyers (ou redevances) payé par les occupants","OEO1","Loyers (ou redevances) payé par les occupants","OEO112","Loyers imputés"],
  ["OE","Dépenses des occupants","OEO1","Loyers (ou redevances) payé par les occupants","OEO1","Loyers (ou redevances) payé par les occupants","OEO113","Droit au bail"],
  ["OE","Dépenses des occupants","OEO1","Loyers (ou redevances) payé par les occupants","OEO1","Loyers (ou redevances) payé par les occupants","OEO12","Redevances occupants (FL2 uniquement)"],
  ["OE","Dépenses des occupants","OEOb","Charges","OEO2","Energie","OEO211","Energie-Electricité"],
  ["OE","Dépenses des occupants","OEOb","Charges","OEO2","Energie","OEO212","Energie-Gaz"],
  ["OE","Dépenses des occupants","OEOb","Charges","OEO2","Energie","OEO210","Energie-Produits pétroliers"],
  ["OE","Dépenses des occupants","OEOb","Charges","OEO2","Energie","OEO217","Energie-Bois"],
  ["OE","Dépenses des occupants","OEOb","Charges","OEO2","Energie","OEO219","Energie-Autres"],
  ["OE","Dépenses des occupants","OEOb","Charges","OEO2","Energie","OEO22","Eau"],
  ["OE","Dépenses des occupants","OEOb","Charges","OEO3a","Autres charges","OEO31","Entretien / travaux parties communes (occupants)"],
  ["OE","Dépenses des occupants","OEOb","Charges","OEO3a","Autres charges","OEO41","Entretien / travaux dans le logement"],
  ["OE","Dépenses des occupants","OEOb","Charges","OEO3a","Autres charges","OEO42","Service d'assurances"],
  ["OE","Dépenses des occupants","OEOb","Charges","OEO3a","Autres charges","OEO51","Gardiens d'immeubles (occupants)"],
  ["OE","Dépenses des occupants","OEOb","Charges","OEO3a","Autres charges","OEO61","Prestations de services occupants (TEOM, REOM, TB…)"],
  ["OE","Dépenses des occupants","OEOb","Charges","OEO3a","Autres charges","OEO62","Déménagement"],
  ["OE","Dépenses des occupants","OEOb","Charges","OEO3a","Autres charges","OEO63","Frais de baux (occupants)"],
  ["OP","Compte des bailleurs","OEP","Baill. - Emplois","OEP1a","Charges","OEP11","Entretien / travaux parties communes (bailleurs)"],
  ["OP","Compte des bailleurs","OEP","Baill. - Emplois","OEP1a","Charges","OEP12","Energie-Eau (logements vacants)"],
  ["OP","Compte des bailleurs","OEP","Baill. - Emplois","OEP1a","Charges","OEP12","Energie-Eau (logements vacants)"],
  ["OP","Compte des bailleurs","OEP","Baill. - Emplois","OEP1a","Charges","OEP12","Energie-Eau (logements vacants)"],
  ["OP","Compte des bailleurs","OEP","Baill. - Emplois","OEP1a","Charges","OEP12","Energie-Eau (logements vacants)"],
  ["OP","Compte des bailleurs","OEP","Baill. - Emplois","OEP1a","Charges","OEP12","Energie-Eau (logements vacants)"],
  ["OP","Compte des bailleurs","OEP","Baill. - Emplois","OEP1a","Charges","OEP12","Energie-Eau (logements vacants)"],
  ["OP","Compte des bailleurs","OEP","Baill. - Emplois","OEP1a","Charges","OEP21","Honoraires de syndic"],
  ["OP","Compte des bailleurs","OEP","Baill. - Emplois","OEP1a","Charges","OEP22","Petits travaux dans les logements"],
  ["OP","Compte des bailleurs","OEP","Baill. - Emplois","OEP1a","Charges","OEP23","Frais de gestion locative"],
  ["OP","Compte des bailleurs","OEP","Baill. - Emplois","OEP1a","Charges","OEP24","Primes d'assurances"],
  ["OP","Compte des bailleurs","OEP","Baill. - Emplois","OEP1a","Charges","OEP31","Gardiens d'immeubles (bailleurs)"],
  ["OP","Compte des bailleurs","OEP","Baill. - Emplois","OEP1a","Charges","OEP32","Personnel de gestion"],
  ["OP","Compte des bailleurs","OEP","Baill. - Emplois","OEP4a","Impôts - Redevances","OEP41","TFPB"],
  ["OP","Compte des bailleurs","OEP","Baill. - Emplois","OEP4a","Impôts - Redevances","OEP421","IRPP"],
  ["OP","Compte des bailleurs","OEP","Baill. - Emplois","OEP4a","Impôts - Redevances","OEP422","CSG"],
  ["OP","Compte des bailleurs","OEP","Baill. - Emplois","OEP4a","Impôts - Redevances","OEP423","CRDS"],
  ["OP","Compte des bailleurs","OEP","Baill. - Emplois","OEP4a","Impôts - Redevances","OEP424","Prélèvement social"],
  ["OP","Compte des bailleurs","OEP","Baill. - Emplois","OEP4a","Impôts - Redevances","OEP425","IS"],
  ["OP","Compte des bailleurs","OEP","Baill. - Emplois","OEP4a","Impôts - Redevances","OEP429","Autres impôts sur la production de service de logement"],
  ["OP","Compte des bailleurs","OEP","Baill. - Emplois","OEP1a","Charges","OEP51","Intérêts des emprunts"],
  ["OP","Compte des bailleurs","OEP","Baill. - Emplois","OEP4a","Impôts - Redevances","OEP61","Prestations de services bailleurs (TEOM, REOM, TB…)"],
  ["OP","Compte des bailleurs","OEP","Baill. - Emplois","OEP1a","Charges","OEP62","Frais de baux (bailleurs)"],
  ["OP","Compte des bailleurs","OEP","Baill. - Emplois","OEP1a","Charges","OEP8","Loyers imputés pour les logés gratuits"],
  ["OP","Compte des bailleurs","OEPR","Baill. - Ressources","OEPR1","Loyers (ou redevances) perçus par le bailleur","OEPR111","Loyers réels des locataires"],
  ["OP","Compte des bailleurs","OEPR","Baill. - Ressources","OEPR1","Loyers (ou redevances) perçus par le bailleur","OEPR112","Loyers imputés des propriétaires occupants (et RS)"],
  ["OP","Compte des bailleurs","OEPR","Baill. - Ressources","OEPR1","Loyers (ou redevances) perçus par le bailleur","OEPR113","Contributions sur les revenus locatifs"],
  ["OP","Compte des bailleurs","OEPR","Baill. - Ressources","OEPR1","Loyers (ou redevances) perçus par le bailleur","OEPR114","Taxe sur le dépassement du plafond légal de ressources"],
  ["OP","Compte des bailleurs","OEPR","Baill. - Ressources","OEPR1","Loyers (ou redevances) perçus par le bailleur","OEPR12","Redevances bailleurs (FL2 uniquement)"],
  ["OP","Compte des bailleurs","OEPR","Baill. - Ressources","OEPR2","Autres ressources","OEPR21","Subventions à la production de service de logement"],
  ["OP","Compte des bailleurs","OEPR","Baill. - Ressources","OEPR2","Autres ressources","OEPR22","Avantages fiscaux à la production de service de logement"],
  ["OP","Compte des bailleurs","OEPR","Baill. - Ressources","OEPR2","Autres ressources","OEPR31","Indemnités d assurances"],
  ["OF","Financement de l’activité immobilère","OFAT","Financement","OFAT1","Fin. Neuf","OFAT11","Neuf - Fonds propres"],
  ["OF","Financement de l’activité immobilère","OFAT","Financement","OFAT1","Fin. Neuf","OFAT12","Neuf - Aides à l investissement"],
  ["OF","Financement de l’activité immobilère","OFAT","Financement","OFAT1","Fin. Neuf","OFAT131","Neuf - Crédits aidés"],
  ["OF","Financement de l’activité immobilère","OFAT","Financement","OFAT1","Fin. Neuf","OFAT132","Neuf - Crédits non aidés"],
  ["OF","Financement de l’activité immobilère","OFAT","Financement","OFAT2","Fin. Ancien","OFAT21","Ancien – Fonds propres"],
  ["OF","Financement de l’activité immobilère","OFAT","Financement","OFAT2","Fin. Ancien","OFAT21","Ancien – Fonds propres"],
  ["OF","Financement de l’activité immobilère","OFAT","Financement","OFAT2","Fin. Ancien","OFAT21","Ancien – Fonds propres"],
  ["OF","Financement de l’activité immobilère","OFAT","Financement","OFAT2","Fin. Ancien","OFAT21","Ancien – Fonds propres"],
  ["OF","Financement de l’activité immobilère","OFAT","Financement","OFAT2","Fin. Ancien","OFAT22","Ancien - Aides à l investissement"],
  ["OF","Financement de l’activité immobilère","OFAT","Financement","OFAT2","Fin. Ancien","OFAT231","Ancien - Crédits aidés"],
  ["OF","Financement de l’activité immobilère","OFAT","Financement","OFAT2","Fin. Ancien","OFAT232","Ancien - Crédits non aidés"],
  ["OF","Financement de l’activité immobilère","OFAT","Financement","OFAT3","Fin. Travaux","OFAT31","Travaux - Fonds propres"],
  ["OF","Financement de l’activité immobilère","OFAT","Financement","OFAT3","Fin. Travaux","OFAT32","Travaux - Aides à l investissement"],
  ["OF","Financement de l’activité immobilère","OFAT","Financement","OFAT3","Fin. Travaux","OFAT331","Travaux - Crédits aidés"],
  ["OF","Financement de l’activité immobilère","OFAT","Financement","OFAT3","Fin. Travaux","OFAT332","Travaux - Crédits non aidés"],
  ["OI","Activité immobilière","OIL","Acquisitions","OIL1","Achat Neuf","OIL11","Logements neufs hors terrains"],
  ["OI","Activité immobilière","OIL","Acquisitions","OIL1","Achat Neuf","OIL12","Terrains d'assise"],
  ["OI","Activité immobilière","OIL","Acquisitions","OIL1","Achat Neuf","OIL13","Frais relatifs aux logements neufs (yc terrains)"],
  ["OI","Activité immobilière","OIL","Acquisitions","OIL1","Achat Neuf","OIL14","Droits de mutation relatifs aux logements neufs (yc terrains)"],
  ["OI","Activité immobilière","OIL","Acquisitions","OIL2","Gros travaux sur logements existants","OIL2","Gros travaux sur logements existants"],
  ["OI","Activité immobilière","OIL","Acquisitions","OIL3","Achat Ancien","OIL31","Acquisitions de logements d'occasion (hors terrain)"],
  ["OI","Activité immobilière","OIL","Acquisitions","OIL3","Achat Ancien","OIL32","Terrains des logements d'occasion acquis"],
  ["OI","Activité immobilière","OIL","Acquisitions","OIL3","Achat Ancien","OIL33","Frais relatifs aux logements d'occasion (yc terrains)"],
  ["OI","Activité immobilière","OIL","Acquisitions","OIL3","Achat Ancien","OIL34","Droits de mutation relatifs aux logements d'occasion (yc terrains)"],
  ["AID","Aides au logement","AID1","Aides personnelles","AID101","APL","AID101","APL"],
  ["AID","Aides au logement","AID1","Aides personnelles","AID102","ALS","AID102","ALS"],
  ["AID","Aides au logement","AID1","Aides personnelles","AID103","ALF","AID103","ALF"],
  ["AID","Aides au logement","AID1","Aides personnelles","AID104a","Autres aides perso","AID104a","Autres aides perso"],
  ["AID","Aides au logement","AID1","Aides personnelles","AID104a","Autres aides perso","AID104a","Autres aides perso"],
  ["AID","Aides au logement","AID1","Aides personnelles","AID104a","Autres aides perso","AID104a","Autres aides perso"],
  ["AID","Aides au logement","AID1","Aides personnelles","AID104a","Autres aides perso","AID104a","Autres aides perso"],
  ["AID","Aides au logement","AID2","Subventions d'exploitation","AID20","Sub exploit éteintes","AID20","Sub exploit éteintes"],
  ["AID","Aides au logement","AID2","Subventions d'exploitation","AID20","Sub exploit éteintes","AID20","Sub exploit éteintes"],
  ["AID","Aides au logement","AID2","Subventions d'exploitation","AID20","Sub exploit éteintes","AID20","Sub exploit éteintes"],
  ["AID","Aides au logement","AID2","Subventions d'exploitation","AID20","Sub exploit éteintes","AID20","Sub exploit éteintes"],
  ["AID","Aides au logement","AID2","Subventions d'exploitation","AID20","Sub exploit éteintes","AID20","Sub exploit éteintes"],
  ["AID","Aides au logement","AID2","Subventions d'exploitation","AID20","Sub exploit éteintes","AID20","Sub exploit éteintes"],
  ["AID","Aides au logement","AID2","Subventions d'exploitation","AID20","Sub exploit éteintes","AID20","Sub exploit éteintes"],
  ["AID","Aides au logement","AID2","Subventions d'exploitation","AID20","Sub exploit éteintes","AID20","Sub exploit éteintes"],
  ["AID","Aides au logement","AID2","Subventions d'exploitation","AID20","Sub exploit éteintes","AID20","Sub exploit éteintes"],
  ["AID","Aides au logement","AID2","Subventions d'exploitation","AID20","Sub exploit éteintes","AID20","Sub exploit éteintes"],
  ["AID","Aides au logement","AID2","Subventions d'exploitation","AID20","Sub exploit éteintes","AID20","Sub exploit éteintes"],
  ["AID","Aides au logement","AID2","Subventions d'exploitation","AID20","Sub exploit éteintes","AID20","Sub exploit éteintes"],
  ["AID","Aides au logement","AID2","Subventions d'exploitation","AID20","Sub exploit éteintes","AID20","Sub exploit éteintes"],
  ["AID","Aides au logement","AID2","Subventions d'exploitation","AID24","Sub exploit locaux","AID24","Sub exploit locaux"],
  ["AID","Aides au logement","AID3","Subventions d'investissement","AID3N","Aides - Neuf","AID301N","Subv PLS Neuf"],
  ["AID","Aides au logement","AID3","Subventions d'investissement","AID3A","Aides - Ancien","AID301A","Subv PLS Ancien"],
  ["AID","Aides au logement","AID3","Subventions d'investissement","AID3T","Aides - Travaux","AID301T","Subv PLS Travaux"],
  ["AID","Aides au logement","AID3","Subventions d'investissement","AID3N","Aides - Neuf","AID301N","Subv PLS Neuf"],
  ["AID","Aides au logement","AID3","Subventions d'investissement","AID3A","Aides - Ancien","AID301A","Subv PLS Ancien"],
  ["AID","Aides au logement","AID3","Subventions d'investissement","AID3T","Aides - Travaux","AID301T","Subv PLS Travaux"],
  ["AID","Aides au logement","AID3","Subventions d'investissement","AID3N","Aides - Neuf","AID301N","Subv PLS Neuf"],
  ["AID","Aides au logement","AID3","Subventions d'investissement","AID3A","Aides - Ancien","AID301A","Subv PLS Ancien"],
  ["AID","Aides au logement","AID3","Subventions d'investissement","AID3T","Aides - Travaux","AID301T","Subv PLS Travaux"],
  ["AID","Aides au logement","AID3","Subventions d'investissement","AID3N","Aides - Neuf","AID301N","Subv PLS Neuf"],
  ["AID","Aides au logement","AID3","Subventions d'investissement","AID3A","Aides - Ancien","AID301A","Subv PLS Ancien"],
  ["AID","Aides au logement","AID3","Subventions d'investissement","AID3T","Aides - Travaux","AID301T","Subv PLS Travaux"],
  ["AID","Aides au logement","AID3","Subventions d'investissement","AID3T","Aides - Travaux","AID301T","Subv PLS Travaux"],
  ["AID","Aides au logement","AID3","Subventions d'investissement","AID3N","Aides - Neuf","AID301N","Subv PLS Neuf"],
  ["AID","Aides au logement","AID3","Subventions d'investissement","AID3A","Aides - Ancien","AID301A","Subv PLS Ancien"],
  ["AID","Aides au logement","AID3","Subventions d'investissement","AID3T","Aides - Travaux","AID301T","Subv PLS Travaux"],
  ["AID","Aides au logement","AID3","Subventions d'investissement","AID3N","Aides - Neuf","AID310N","Subv autres Neuf"],
  ["AID","Aides au logement","AID3","Subventions d'investissement","AID3N","Aides - Neuf","AID303N","ANRU Neuf"],
  ["AID","Aides au logement","AID3","Subventions d'investissement","AID3T","Aides - Travaux","AID303T","ANRU Travaux"],
  ["AID","Aides au logement","AID3","Subventions d'investissement","AID3T","Aides - Travaux","AID306T","ANAH - PAH Aides - Travaux"],
  ["AID","Aides au logement","AID3","Subventions d'investissement","AID3T","Aides - Travaux","AID307T","Subv autres Travaux"],
  ["AID","Aides au logement","AID3","Subventions d'investissement","AID3N","Aides - Neuf","AID308N","Subv Action Logement Aides - Neuf"],
  ["AID","Aides au logement","AID3","Subventions d'investissement","AID3A","Aides - Ancien","AID308A","Subv Action Logement Aides - Ancien"],
  ["AID","Aides au logement","AID3","Subventions d'investissement","AID3T","Aides - Travaux","AID308T","Subv Action Logement Aides - Travaux"],
  ["AID","Aides au logement","AID3","Subventions d'investissement","AID3T","Aides - Travaux","AID306T","ANAH - PAH Aides - Travaux"],
  ["AID","Aides au logement","AID3","Subventions d'investissement","AID3N","Aides - Neuf","AID310N","Subv autres Neuf"],
  ["AID","Aides au logement","AID3","Subventions d'investissement","AID3N","Aides - Neuf","AID310N","Subv autres Neuf"],
  ["AID","Aides au logement","AID3","Subventions d'investissement","AID3N","Aides - Neuf","AID311N","Subv PLS Coll Terr Aides - Neuf"],
  ["AID","Aides au logement","AID3","Subventions d'investissement","AID3N","Aides - Neuf","AID311N","Subv PLS Coll Terr Aides - Neuf"],
  ["AID","Aides au logement","AID3","Subventions d'investissement","AID3A","Aides - Ancien","AID311A","Subv PLS Coll Terr Aides - Ancien"],
  ["AID","Aides au logement","AID3","Subventions d'investissement","AID3T","Aides - Travaux","AID311T","Subv PLS Coll Terr Aides - Travaux"],
  ["AID","Aides au logement","AID3","Subventions d'investissement","AID3N","Aides - Neuf","AID311N","Subv PLS Coll Terr Aides - Neuf"],
  ["AID","Aides au logement","AID3","Subventions d'investissement","AID3N","Aides - Neuf","AID311N","Subv PLS Coll Terr Aides - Neuf"],
  ["AID","Aides au logement","AID3","Subventions d'investissement","AID3A","Aides - Ancien","AID311A","Subv PLS Coll Terr Aides - Ancien"],
  ["AID","Aides au logement","AID3","Subventions d'investissement","AID3T","Aides - Travaux","AID311T","Subv PLS Coll Terr Aides - Travaux"],
  ["AID","Aides au logement","AID3","Subventions d'investissement","AID3N","Aides - Neuf","AID311N","Subv PLS Coll Terr Aides - Neuf"],
  ["AID","Aides au logement","AID3","Subventions d'investissement","AID3A","Aides - Ancien","AID311A","Subv PLS Coll Terr Aides - Ancien"],
  ["AID","Aides au logement","AID3","Subventions d'investissement","AID3T","Aides - Travaux","AID311T","Subv PLS Coll Terr Aides - Travaux"],
  ["AID","Aides au logement","AID3","Subventions d'investissement","AID3N","Aides - Neuf","AID311N","Subv PLS Coll Terr Aides - Neuf"],
  ["AID","Aides au logement","AID3","Subventions d'investissement","AID3A","Aides - Ancien","AID311A","Subv PLS Coll Terr Aides - Ancien"],
  ["AID","Aides au logement","AID3","Subventions d'investissement","AID3T","Aides - Travaux","AID311T","Subv PLS Coll Terr Aides - Travaux"],
  ["AID","Aides au logement","AID3","Subventions d'investissement","AID3T","Aides - Travaux","AID311T","Subv PLS Coll Terr Aides - Travaux"],
  ["AID","Aides au logement","AID3","Subventions d'investissement","AID3N","Aides - Neuf","AID311N","Subv PLS Coll Terr Aides - Neuf"],
  ["AID","Aides au logement","AID3","Subventions d'investissement","AID3A","Aides - Ancien","AID311A","Subv PLS Coll Terr Aides - Ancien"],
  ["AID","Aides au logement","AID3","Subventions d'investissement","AID3T","Aides - Travaux","AID311T","Subv PLS Coll Terr Aides - Travaux"],
  ["AID","Aides au logement","AID3","Subventions d'investissement","AID3T","Aides - Travaux","AID306T","ANAH - PAH Aides - Travaux"],
  ["AID","Aides au logement","AID3","Subventions d'investissement","AID3T","Aides - Travaux","AID306T","ANAH - PAH Aides - Travaux"],
  ["AID","Aides au logement","AID3","Subventions d'investissement","AID3N","Aides - Neuf","AID308N","Subv Action Logement Aides - Neuf"],
  ["AID","Aides au logement","AID3","Subventions d'investissement","AID3T","Aides - Travaux","AID307T","Subv autres Travaux"],
  ["AID","Aides au logement","AID3","Subventions d'investissement","AID3T","Aides - Travaux","AID307T","Subv autres Travaux"],
  ["AID","Aides au logement","AID3","Subventions d'investissement","AID3A","Aides - Ancien","AID307A","Subv autres Ancien"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID44","Autres avantages fiscaux","AID44a","Autres dispositifs fiscaux"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID44","Autres avantages fiscaux","AID44a","Autres dispositifs fiscaux"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID41","TVA réduite","AID411","TVA réduite pour travaux"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID41","TVA réduite","AID411","TVA réduite pour travaux"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID41","TVA réduite","AID411","TVA réduite pour travaux"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID42","Allégement IR","AID423","Réduction ou crédit d’impôt rénovation"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID41","TVA réduite","AID411","TVA réduite pour travaux"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID42","Allégement IR","AID422","Autres allégement IR"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID42","Allégement IR","AID423","Réduction ou crédit d’impôt rénovation"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID44","Autres avantages fiscaux","AID44a","Autres dispositifs fiscaux"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID42","Allégement IR","AID421","Investissement locatif"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID44","Autres avantages fiscaux","AID44a","Autres dispositifs fiscaux"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID44","Autres avantages fiscaux","AID44a","Autres dispositifs fiscaux"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID44","Autres avantages fiscaux","AID44a","Autres dispositifs fiscaux"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID44","Autres avantages fiscaux","AID44b","Exonération IS"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID43","Allègement impôts locaux","AID431","Exonération TFPB"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID42","Allégement IR","AID421","Investissement locatif"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID42","Allégement IR","AID422","Autres allégement IR"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID44","Autres avantages fiscaux","AID44a","Autres dispositifs fiscaux"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID42","Allégement IR","AID423","Réduction ou crédit d’impôt rénovation"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID42","Allégement IR","AID423","Réduction ou crédit d’impôt rénovation"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID41","TVA réduite","AID411","TVA réduite pour travaux"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID41","TVA réduite","AID412","TVA réduite pour acquisition"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID41","TVA réduite","AID411","TVA réduite pour travaux"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID41","TVA réduite","AID412","TVA réduite pour acquisition"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID41","TVA réduite","AID412","TVA réduite pour acquisition"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID42","Allégement IR","AID421","Investissement locatif"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID42","Allégement IR","AID421","Investissement locatif"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID44","Autres avantages fiscaux","AID44a","Autres dispositifs fiscaux"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID42","Allégement IR","AID421","Investissement locatif"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID42","Allégement IR","AID421","Investissement locatif"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID41","TVA réduite","AID412LS","TVA réduite pour acquisition,  logement social"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID41","TVA réduite","AID411LS","TVA réduite pour travaux,  logement social"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID41","TVA réduite","AID412LS","TVA réduite pour acquisition,  logement social"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID41","TVA réduite","AID411LS","TVA réduite pour travaux,  logement social"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID41","TVA réduite","AID412LS","TVA réduite pour acquisition,  logement social"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID41","TVA réduite","AID411LS","TVA réduite pour travaux,  logement social"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID41","TVA réduite","AID412LS","TVA réduite pour acquisition,  logement social"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID41","TVA réduite","AID411LS","TVA réduite pour travaux,  logement social"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID41","TVA réduite","AID411LS","TVA réduite pour travaux,  logement social"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID41","TVA réduite","AID412LS","TVA réduite pour acquisition,  logement social"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID41","TVA réduite","AID411LS","TVA réduite pour travaux,  logement social"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID41","TVA réduite","AID411LS","TVA réduite pour travaux,  logement social"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID43","Allègement impôts locaux","AID431","Exonération TFPB"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID44","Autres avantages fiscaux","AID44a","Autres dispositifs fiscaux"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID42","Allégement IR","AID422","Autres allégement IR"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID42","Allégement IR","AID421","Investissement locatif"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID42","Allégement IR","AID421","Investissement locatif"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID42","Allégement IR","AID421","Investissement locatif"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID42","Allégement IR","AID421","Investissement locatif"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID42","Allégement IR","AID421","Investissement locatif"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID42","Allégement IR","AID421","Investissement locatif"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID42","Allégement IR","AID421","Investissement locatif"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID42","Allégement IR","AID421","Investissement locatif"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID42","Allégement IR","AID421","Investissement locatif"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID41","TVA réduite","AID412","TVA réduite pour acquisition"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID41","TVA réduite","AID411","TVA réduite pour travaux"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID42","Allégement IR","AID421","Investissement locatif"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID42","Allégement IR","AID421","Investissement locatif"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID42","Allégement IR","AID421","Investissement locatif"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID42","Allégement IR","AID421","Investissement locatif"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID43","Allègement impôts locaux","AID431","Exonération TFPB"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID43","Allègement impôts locaux","AID431","Exonération TFPB"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID43","Allègement impôts locaux","AID431","Exonération TFPB"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID43","Allègement impôts locaux","AID431","Exonération TFPB"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID43","Allègement impôts locaux","AID431","Exonération TFPB"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID43","Allègement impôts locaux","AID431","Exonération TFPB"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID43","Allègement impôts locaux","AID431","Exonération TFPB"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID43","Allègement impôts locaux","AID431","Exonération TFPB"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID41","TVA réduite","AID411","TVA réduite pour travaux"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID42","Allégement IR","AID423","Réduction ou crédit d’impôt rénovation"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID42","Allégement IR","AID421","Investissement locatif"],
  ["AID","Aides au logement","AID5","Avantages de taux","AID51","AvTaux - Bailleurs sociaux","AID501","PLS"],
  ["AID","Aides au logement","AID5","Avantages de taux","AID51","AvTaux - Bailleurs sociaux","AID502","PLAI"],
  ["AID","Aides au logement","AID5","Avantages de taux","AID51","AvTaux - Bailleurs sociaux","AID503","PLUS"],
  ["AID","Aides au logement","AID5","Avantages de taux","AID51","AvTaux - Bailleurs sociaux","AID50a","Prêts aux bailleurs - Autres"],
  ["AID","Aides au logement","AID5","Avantages de taux","AID51","AvTaux - Bailleurs sociaux","AID50a","Prêts aux bailleurs - Autres"],
  ["AID","Aides au logement","AID5","Avantages de taux","AID51","AvTaux - Bailleurs sociaux","AID50a","Prêts aux bailleurs - Autres"],
  ["AID","Aides au logement","AID5","Avantages de taux","AID51","AvTaux - Bailleurs sociaux","AID50a","Prêts aux bailleurs - Autres"],
  ["AID","Aides au logement","AID5","Avantages de taux","AID51","AvTaux - Bailleurs sociaux","AID50a","Prêts aux bailleurs - Autres"],
  ["AID","Aides au logement","AID5","Avantages de taux","AID51","AvTaux - Bailleurs sociaux","AID50a","Prêts aux bailleurs - Autres"],
  ["AID","Aides au logement","AID5","Avantages de taux","AID52","AvTaux - Ménages","AID50b","Prêts aux ménages - Autres"],
  ["AID","Aides au logement","AID5","Avantages de taux","AID51","AvTaux - Bailleurs sociaux","AID50a","Prêts aux bailleurs - Autres"],
  ["AID","Aides au logement","AID5","Avantages de taux","AID52","AvTaux - Ménages","AID50b","Prêts aux ménages - Autres"],
  ["AID","Aides au logement","AID5","Avantages de taux","AID52","AvTaux - Ménages","AID511","PTZ (prêt à taux zéro) "],
  ["AID","Aides au logement","AID5","Avantages de taux","AID52","AvTaux - Ménages","AID512","ECO-PTZ (éco-prêt à taux zéro) "],
  ["AID","Aides au logement","AID5","Avantages de taux","AID52","AvTaux - Ménages","AID50b","Prêts aux ménages - Autres"],
  ["AID","Aides au logement","AID5","Avantages de taux","AID52","AvTaux - Ménages","AID50b","Prêts aux ménages - Autres"],
  ["AID","Aides au logement","AID5","Avantages de taux","AID52","AvTaux - Ménages","AID50b","Prêts aux ménages - Autres"],
  ["AID","Aides au logement","AID5","Avantages de taux","AID52","AvTaux - Ménages","AID50b","Prêts aux ménages - Autres"],
  ["AID","Aides au logement","AID5","Avantages de taux","AID52","AvTaux - Ménages","AID517","PLUS Anru"],
  ["AID","Aides au logement","AID5","Avantages de taux","AID52","AvTaux - Ménages","AID518","PLAI Anru"],
  ["OPL","Parc – Logements","OPL1","Logements – Individuel","OPL1","Logements – Individuel","OPL1","Logements – Individuel"],
  ["OPL","Parc – Logements","OPL2","Logements – Groupé","OPL2","Logements – Groupé","OPL2","Logements – Groupé"],
  ["OPS","Parc – Surfaces","OPS1","Surfaces – Individuel","OPS1","Surfaces – Individuel","OPS1","Surfaces – Individuel"],
  ["OPS","Parc – Surfaces","OPS2","Surfaces – Groupé","OPS2","Surfaces – Groupé","OPS2","Surfaces – Groupé"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID41","TVA réduite","AID413","Autre TVA réduite"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID41","TVA réduite","AID412","TVA réduite pour acquisition"],
  ["AID","Aides au logement","AID4","Avantages fiscaux","AID42","Allégement IR","AID421","Investissement locatif"]
]
