module.exports = [
  ["FR01","FRANCE: Atlantic and North Sea","FRAUD","Audierne"],
  ["FR01","FRANCE: Atlantic and North Sea","FRBAI","Basse-Indre"],
  ["FR01","FRANCE: Atlantic and North Sea","FRBAS","Bassens"],
  ["FR01","FRANCE: Atlantic and North Sea","FRBAY","Bayonne"],
  ["FR01","FRANCE: Atlantic and North Sea","FRBDE","Bénodet"],
  ["FR01","FRANCE: Atlantic and North Sea","FRBEC","Bec d'Ambes"],
  ["FR01","FRANCE: Atlantic and North Sea","FRBES","Brest"],
  ["FR01","FRANCE: Atlantic and North Sea","FRBH4","Bourcefranc-le-Chapus"],
  ["FR01","FRANCE: Atlantic and North Sea","FRBOD","Bordeaux"],
  ["FR01","FRANCE: Atlantic and North Sea","FRBOL","Boulogne-sur-Mer"],
  ["FR01","FRANCE: Atlantic and North Sea","FRBSC","Bonsecours"],
  ["FR01","FRANCE: Atlantic and North Sea","FRBYE","Blaye"],
  ["FR01","FRANCE: Atlantic and North Sea","FRCAM","Camaret-sur-Mer"],
  ["FR01","FRANCE: Atlantic and North Sea","FRCER","Cherbourg"],
  ["FR01","FRANCE: Atlantic and North Sea","FRCFR","Caen Ouistreham"],
  ["FR01","FRANCE: Atlantic and North Sea","FRCOC","Concarneau"],
  ["FR01","FRANCE: Atlantic and North Sea","FRCQF","Calais"],
  ["FR01","FRANCE: Atlantic and North Sea","FRDCG","Saint-Cast-le-Guildo"],
  ["FR01","FRANCE: Atlantic and North Sea","FRDIL","Flamanville (port de Diélette)"],
  ["FR01","FRANCE: Atlantic and North Sea","FRDKK","Dunkerque"],
  ["FR01","FRANCE: Atlantic and North Sea","FRDON","Donges"],
  ["FR01","FRANCE: Atlantic and North Sea","FRDPE","Dieppe"],
  ["FR01","FRANCE: Atlantic and North Sea","FRDRZ","Douarnenez"],
  ["FR01","FRANCE: Atlantic and North Sea","FRDUT","Lanildut"],
  ["FR01","FRANCE: Atlantic and North Sea","FRECQ","Le Conquet"],
  ["FR01","FRANCE: Atlantic and North Sea","FRFEC","Fécamp"],
  ["FR01","FRANCE: Atlantic and North Sea","FRFUS","Fouesnant (port de Beg Meil)"],
  ["FR01","FRANCE: Atlantic and North Sea","FRGFR","Granville"],
  ["FR01","FRANCE: Atlantic and North Sea","FRGLO","Gonfreville-l'Orcher"],
  ["FR01","FRANCE: Atlantic and North Sea","FRHCN","Clohars-Carnoët (port de Doëlan)"],
  ["FR01","FRANCE: Atlantic and North Sea","FRHET","Hennebont"],
  ["FR01","FRANCE: Atlantic and North Sea","FRHON","Honfleur"],
  ["FR01","FRANCE: Atlantic and North Sea","FRHRF","Harfleur"],
  ["FR01","FRANCE: Atlantic and North Sea","FRLDN","Landerneau"],
  ["FR01","FRANCE: Atlantic and North Sea","FRLEH","Le Havre"],
  ["FR01","FRANCE: Atlantic and North Sea","FRLEZ","Lézardrieux"],
  ["FR01","FRANCE: Atlantic and North Sea","FRLLG","Le Légué"],
  ["FR01","FRANCE: Atlantic and North Sea","FRLOC","Loctudy"],
  ["FR01","FRANCE: Atlantic and North Sea","FRLPE","La Pallice"],
  ["FR01","FRANCE: Atlantic and North Sea","FRLRH","La Rochelle"],
  ["FR01","FRANCE: Atlantic and North Sea","FRLRQ","Locmariaquer"],
  ["FR01","FRANCE: Atlantic and North Sea","FRLRT","Lorient"],
  ["FR01","FRANCE: Atlantic and North Sea","FRLSO","Les Sables d'Olonne"],
  ["FR01","FRANCE: Atlantic and North Sea","FRLT3","La Tranche-sur-Mer"],
  ["FR01","FRANCE: Atlantic and North Sea","FRLTR","Le Tréport"],
  ["FR01","FRANCE: Atlantic and North Sea","FRLVE","Le Verdon"],
  ["FR01","FRANCE: Atlantic and North Sea","FRLZF","La Forêt Fouesnant (port de Port-la-Forêt)"],
  ["FR01","FRANCE: Atlantic and North Sea","FRMN4","Montoire"],
  ["FR01","FRANCE: Atlantic and North Sea","FRMTX","Montoir-de-Bretagne"],
  ["FR01","FRANCE: Atlantic and North Sea","FRNOP","Baden (port de Port-Blanc)"],
  ["FR01","FRANCE: Atlantic and North Sea","FRNTE","Nantes Saint-Nazaire"],
  ["FR01","FRANCE: Atlantic and North Sea","FROII","Le Croisic"],
  ["FR01","FRANCE: Atlantic and North Sea","FROLU","Port-Louis"],
  ["FR01","FRANCE: Atlantic and North Sea","FROQL","Locmiquélic"],
  ["FR01","FRANCE: Atlantic and North Sea","FROZA","Ploubazlanec"],
  ["FR01","FRANCE: Atlantic and North Sea","FRPAP","Pauillac-Port"],
  ["FR01","FRANCE: Atlantic and North Sea","FRPBF","Paimboeuf"],
  ["FR01","FRANCE: Atlantic and North Sea","FRPET","Petit Couronne"],
  ["FR01","FRANCE: Atlantic and North Sea","FRPJE","Port Jérôme"],
  ["FR01","FRANCE: Atlantic and North Sea","FRPOX","Pontrieux"],
  ["FR01","FRANCE: Atlantic and North Sea","FRPRJ","Port-Joinville (Île d’Yeu)"],
  ["FR01","FRANCE: Atlantic and North Sea","FRQUI","Quiberon (Port Maria et Port Haligen)"],
  ["FR01","FRANCE: Atlantic and North Sea","FRRAD","Radicatel"],
  ["FR01","FRANCE: Atlantic and North Sea","FRRCO","Rochefort"],
  ["FR01","FRANCE: Atlantic and North Sea","FRRDN","Redon"],
  ["FR01","FRANCE: Atlantic and North Sea","FRROS","Roscoff"],
  ["FR01","FRANCE: Atlantic and North Sea","FRRYN","Royan"],
  ["FR01","FRANCE: Atlantic and North Sea","FRRZN","Arzon (port de Port-Navalo)"],
  ["FR01","FRANCE: Atlantic and North Sea","FRSML","Saint-Malo"],
  ["FR01","FRANCE: Atlantic and North Sea","FRSNR","Saint-Nazaire"],
  ["FR01","FRANCE: Atlantic and North Sea","FRSWD","Saint-Wandrille"],
  ["FR01","FRANCE: Atlantic and North Sea","FRTBE","La Turballe"],
  ["FR01","FRANCE: Atlantic and North Sea","FRTON","Tonnay Charente"],
  ["FR01","FRANCE: Atlantic and North Sea","FRTRE","Tréguier"],
  ["FR01","FRANCE: Atlantic and North Sea","FRUIP","Quimper"],
  ["FR01","FRANCE: Atlantic and North Sea","FRURO","Rouen"],
  ["FR01","FRANCE: Atlantic and North Sea","FRVNE","Vannes"],
  ["FR01","FRANCE: Atlantic and North Sea","FRXGV","Saint-Gilles-Croix-de-Vie"],
  ["FR01","FRANCE: Atlantic and North Sea","FRXLR","Larmor-Plage"],
  ["FR02","FRANCE: Mediterranean - including Monaco","FRAJA","Ajaccio"],
  ["FR02","FRANCE: Mediterranean - including Monaco","FRALM","Argelès-sur-Mer"],
  ["FR02","FRANCE: Mediterranean - including Monaco","FRAYP","Saint-Cyprien"],
  ["FR02","FRANCE: Mediterranean - including Monaco","FRBEE","Berre"],
  ["FR02","FRANCE: Mediterranean - including Monaco","FRBIA","Bastia"],
  ["FR02","FRANCE: Mediterranean - including Monaco","FRBON","Bonifacio"],
  ["FR02","FRANCE: Mediterranean - including Monaco","FRBY2","Beaulieu-sur-Mer"],
  ["FR02","FRANCE: Mediterranean - including Monaco","FRCEQ","Cannes"],
  ["FR02","FRANCE: Mediterranean - including Monaco","FRCLY","Calvi"],
  ["FR02","FRANCE: Mediterranean - including Monaco","FRCOZ","Caronte"],
  ["FR02","FRANCE: Mediterranean - including Monaco","FRCQK","Cogolin"],
  ["FR02","FRANCE: Mediterranean - including Monaco","FRCVJ","Cavalaire-sur-Mer"],
  ["FR02","FRANCE: Mediterranean - including Monaco","FRETB","Étang-de-Berre"],
  ["FR02","FRANCE: Mediterranean - including Monaco","FRETN","Menton"],
  ["FR02","FRANCE: Mediterranean - including Monaco","FRFOS","Fos-sur-Mer"],
  ["FR02","FRANCE: Mediterranean - including Monaco","FRFRJ","Fréjus (port de Port-Fréjus)"],
  ["FR02","FRANCE: Mediterranean - including Monaco","FRGJU","Vallauris (port de Golfe-Juan)"],
  ["FR02","FRANCE: Mediterranean - including Monaco","FRILR","L´Île Rousse"],
  ["FR02","FRANCE: Mediterranean - including Monaco","FRJLP","Antibes (port de Juan-les Pins)"],
  ["FR02","FRANCE: Mediterranean - including Monaco","FRLAV","Lavéra"],
  ["FR02","FRANCE: Mediterranean - including Monaco","FRLMD","La Mède"],
  ["FR02","FRANCE: Mediterranean - including Monaco","FRLMK","La Londe-les-Maures"],
  ["FR02","FRANCE: Mediterranean - including Monaco","FRLU2","Saint-Mandrier-sur-Mer"],
  ["FR02","FRANCE: Mediterranean - including Monaco","FRLXV","La Croix-Valmer"],
  ["FR02","FRANCE: Mediterranean - including Monaco","FRMND","Mandelieu-la-Napoule"],
  ["FR02","FRANCE: Mediterranean - including Monaco","FRMRS","Marseille"],
  ["FR02","FRANCE: Mediterranean - including Monaco","FRNCE","Nice"],
  ["FR02","FRANCE: Mediterranean - including Monaco","FRNOU","Port-la-Nouvelle"],
  ["FR02","FRANCE: Mediterranean - including Monaco","FRORD","Briord"],
  ["FR02","FRANCE: Mediterranean - including Monaco","FRPDB","Port-de-Bouc"],
  ["FR02","FRANCE: Mediterranean - including Monaco","FRPOV","Port Vendres"],
  ["FR02","FRANCE: Mediterranean - including Monaco","FRPRP","Propriano"],
  ["FR02","FRANCE: Mediterranean - including Monaco","FRPSL","Port-Saint-Louis-du-Rhône "],
  ["FR02","FRANCE: Mediterranean - including Monaco","FRPVO","Porto Vecchio"],
  ["FR02","FRANCE: Mediterranean - including Monaco","FRPYO","Canet-en-Roussillon"],
  ["FR02","FRANCE: Mediterranean - including Monaco","FRRSA","Roquebrune-sur-Argens"],
  ["FR02","FRANCE: Mediterranean - including Monaco","FRSET","Sète"],
  ["FR02","FRANCE: Mediterranean - including Monaco","FRSFP","Six-Fours-les-Plages (port de Brusc)"],
  ["FR02","FRANCE: Mediterranean - including Monaco","FRSRL","Saint-Raphaël"],
  ["FR02","FRANCE: Mediterranean - including Monaco","FRTLN","Toulon"],
  ["FR02","FRANCE: Mediterranean - including Monaco","FRUDD","Grimaud"],
  ["FR02","FRANCE: Mediterranean - including Monaco","FRURU","Collioure"],
  ["FR02","FRANCE: Mediterranean - including Monaco","FRVFM","Villefranche-sur-Mer"],
  ["FR02","FRANCE: Mediterranean - including Monaco","FRVNO","Le Lavandou"],
  ["FR02","FRANCE: Mediterranean - including Monaco","FRXBD","Bandol"],
  ["FR02","FRANCE: Mediterranean - including Monaco","FRYNE","La Seyne-sur-Mer"],
  ["FR02","FRANCE: Mediterranean - including Monaco","FRYNR","Sanary-sur-Mer"],
  ["FR02","FRANCE: Mediterranean - including Monaco","FRZMX","Sainte-Maxime"],
  ["FR03","FRANCE: Guiana","GFCAY","Cayenne"],
  ["FR03","FRANCE: Guiana","GFDDC","Degrad des Cannes (Guyane Française)"],
  ["FR03","FRANCE: Guiana","GFFGE","Fourgassie"],
  ["FR03","FRANCE: Guiana","GFIST","Iles Du Salut"],
  ["FR03","FRANCE: Guiana","GFLVT","Larivot (Guyane Française)"],
  ["FR03","FRANCE: Guiana","GFMCR","Macouria"],
  ["FR03","FRANCE: Guiana","GFMTY","Matoury"],
  ["FR03","FRANCE: Guiana","GFOYP","Saint Georges de l'Oyapock"],
  ["FR03","FRANCE: Guiana","GFPCO","Pariacabo"],
  ["FR03","FRANCE: Guiana","GFQKR","Kourou (Guyane Française)"],
  ["FR03","FRANCE: Guiana","GFREM","Remire"],
  ["FR03","FRANCE: Guiana","GFSLM","Saint-Laurent du Maroni (Guyane Française)"],
  ["FR03","FRANCE: Guiana","GFSMY","Sinnamary"],
  ["FR04","FRANCE: Guadeloupe & Martinique","GPBBR","Basse-Terre (Guadeloupe)"],
  ["FR04","FRANCE: Guadeloupe & Martinique","GPBMH","Baie-Mahault"],
  ["FR04","FRANCE: Guadeloupe & Martinique","GPDSD","La Desirade"],
  ["FR04","FRANCE: Guadeloupe & Martinique","GPFAE","Folle-Anse (Guadeloupe)"],
  ["FR04","FRANCE: Guadeloupe & Martinique","GPGBJ","Marie-Galante"],
  ["FR04","FRANCE: Guadeloupe & Martinique","GPGRB","Grand-Bourg"],
  ["FR04","FRANCE: Guadeloupe & Martinique","GPGUS","Gustavia"],
  ["FR04","FRANCE: Guadeloupe & Martinique","GPJAR","Jarry (Guadeloupe)"],
  ["FR04","FRANCE: Guadeloupe & Martinique","GPLAM","Lamentin"],
  ["FR04","FRANCE: Guadeloupe & Martinique","GPLEM","Le Moule"],
  ["FR04","FRANCE: Guadeloupe & Martinique","GPMSB","Marigot"],
  ["FR04","FRANCE: Guadeloupe & Martinique","GPPTL","Port-Louis"],
  ["FR04","FRANCE: Guadeloupe & Martinique","GPPTP","Pointe-à-Pitre (Guadeloupe)"],
  ["FR04","FRANCE: Guadeloupe & Martinique","GPSFC","Saint-Francois"],
  ["FR04","FRANCE: Guadeloupe & Martinique","GPSFG","Saint-Martin Apt"],
  ["FR04","FRANCE: Guadeloupe & Martinique","GPTRS","Trois-Rivieres"],
  ["FR04","FRANCE: Guadeloupe & Martinique","GPZAA","Pointe-Noire"],
  ["FR04","FRANCE: Guadeloupe & Martinique","MQFDF","Fort-de-France (Martinique)"],
  ["FR04","FRANCE: Guadeloupe & Martinique","MQLER","Le Robert"],
  ["FR04","FRANCE: Guadeloupe & Martinique","MQLFR","Le Francois"],
  ["FR04","FRANCE: Guadeloupe & Martinique","MQLMT","Le Lamentin"],
  ["FR04","FRANCE: Guadeloupe & Martinique","MQLTI","La Trinité"],
  ["FR04","FRANCE: Guadeloupe & Martinique","MQQMR","Le Marin"],
  ["FR04","FRANCE: Guadeloupe & Martinique","MQQPC","Pointe-des-Carrieres"],
  ["FR04","FRANCE: Guadeloupe & Martinique","MQSHL","Scholcher"],
  ["FR04","FRANCE: Guadeloupe & Martinique","MQSPI","Saint-Pierre"],
  ["FR05","FRANCE: La Réunion","REANN","Sainte Anne"],
  ["FR05","FRANCE: La Réunion","REBNT","Saint-Benoît"],
  ["FR05","FRANCE: La Réunion","RECAF","Plaine-des-Cafres"],
  ["FR05","FRANCE: La Réunion","REESH","Etang Sale les Hauts"],
  ["FR05","FRANCE: La Réunion","RELEU","Saint-Leu"],
  ["FR05","FRANCE: La Réunion","RELPT","Le Port"],
  ["FR05","FRANCE: La Réunion","RELTM","Le Tampon"],
  ["FR05","FRANCE: La Réunion","REPAL","Plaine des Palmistes"],
  ["FR05","FRANCE: La Réunion","REPDG","Port Réunion (ex Pointe-des-Galets)"],
  ["FR05","FRANCE: La Réunion","REPOS","Possession"],
  ["FR05","FRANCE: La Réunion","REREU","Réunion"],
  ["FR05","FRANCE: La Réunion","RESLH","La Saline les Hauts"],
  ["FR05","FRANCE: La Réunion","RESLO","Saint-Louis"],
  ["FR05","FRANCE: La Réunion","RESSZ","Sainte Suzanne"]
]
